In [1]:
import pandas as pd

runs = pd.read_csv('rmoi_and_ap_summary_total.csv')
by_run = pd.read_csv('rmoi_and_ap_by_run_total.csv')
runs

,peptide,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
0,ANIMWTIDDA,0.653338,0.189522,1.673403,0.370538,3,3,0.565503,0.523668,0.870842,1.850624,1.922050,1.247535
1,AWIRYDE,0.492994,0.121244,2.056279,0.025024,3,3,0.632445,0.433991,0.412544,2.071116,2.070333,2.027387
2,CEESFR,0.833369,0.033420,1.104380,0.019890,3,3,0.796793,0.862311,0.841003,1.082543,1.109137,1.121459
3,CFMVAVF,0.878688,0.011373,2.985407,0.042653,3,3,0.871235,0.891779,0.873051,2.936173,3.008888,3.011160
4,CGLEVNCL,0.845331,0.093763,1.098466,0.025305,3,3,0.747024,0.855199,0.933770,1.121048,1.103234,1.071115
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,WWLYIWN,0.507293,0.068873,2.868627,0.101548,3,3,0.464792,0.470331,0.586756,2.917796,2.936231,2.751854
95,WWVWE,0.379367,0.083541,2.769770,0.020897,3,3,0.366098,0.303254,0.468748,2.783618,2.745732,2.779959
96,YMRDIATQ,0.360984,0.030441,1.586861,0.017878,3,3,0.369222,0.386457,0.327272,1.567334,1.590827,1.602423
97,YPDYSM,0.419641,0.279942,2.004831,0.033479,3,3,0.737875,0.211401,0.309647,2.035946,2.009141,1.969406
98,YYCDVERMIC,0.374314,0.115319,1.878686,0.043352,3,3,0.307397,0.507472,0.308073,1.917980,1.832180,1.885899

In [2]:
runs_pepmorph = pd.read_csv('rmoi_and_ap_summary_pepmorph.csv')
by_run_pepmorph = pd.read_csv('rmoi_and_ap_by_run_pepmorph.csv')
# remove columns with all NaN values
runs_pepmorph = runs_pepmorph.dropna(axis=1, how='all')
by_run_pepmorph = by_run_pepmorph.dropna(axis=1, how='all')

runs_pepmorph.shape, by_run_pepmorph.shape

((30, 14), (90, 7))

In [3]:
# rename 'morphology' to 'class'
runs_pepmorph = runs_pepmorph.rename(columns={
    'morphology': 'class'
})
by_run_pepmorph = by_run_pepmorph.rename(columns={
    'morphology': 'class'
})

# rename 'fibers' to 'fiber_pepmorph' in class
# and rename 'spheres' to 'sphere_pepmorph' in class

runs_pepmorph['class'] = runs_pepmorph['class'].replace({
    'fibers': 'fiber_pepmorph',
    'spheres': 'sphere_pepmorph'
})

by_run_pepmorph['class'] = by_run_pepmorph['class'].replace({
    'fibers': 'fiber_pepmorph',
    'spheres': 'sphere_pepmorph'
})

runs_pepmorph

,class,peptide,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
0,fiber_pepmorph,CVSAPGIFHC,0.376627,0.070951,1.959019,0.058305,3,3,0.295179,0.409692,0.425011,2.022145,1.947726,1.907187
1,fiber_pepmorph,FTFIPGWVDL,0.398661,0.096232,2.439498,0.078677,3,3,0.307051,0.390002,0.498930,2.478425,2.491124,2.348946
2,fiber_pepmorph,HYVSGRFLIY,0.495999,0.025635,2.212450,0.053054,3,3,0.520591,0.497972,0.469435,2.176169,2.187840,2.273340
3,fiber_pepmorph,ILSCPGWPFY,0.257501,0.339623,2.810913,0.009507,3,3,0.240490,0.845007,0.274513,2.817635,2.525681,2.804190
4,fiber_pepmorph,ILSFPDKVTY,0.398988,0.089944,2.194466,0.054625,3,3,0.458935,0.442462,0.295566,2.134727,2.241865,2.206807
5,fiber_pepmorph,LDIYNHPFF,0.264959,0.024398,2.603789,0.017323,3,3,0.278190,0.279883,0.236803,2.585237,2.619542,2.606587
6,fiber_pepmorph,LFLTADSYCF,0.290627,0.036471,2.533485,0.033179,3,3,0.268675,0.270478,0.332727,2.504544,2.526214,2.569697
7,fiber_pepmorph,LICWTGHCHH,0.509004,0.078107,2.225725,0.074194,3,3,0.577594,0.423991,0.525428,2.183927,2.311389,2.181859
8,fiber_pepmorph,PAPFPWSIWI,0.455344,0.127478,3.063479,0.091485,3,3,0.533439,0.308239,0.524355,3.037179,3.165233,2.988025
9,fiber_pepmorph,PFAIPYCSTP,0.603115,0.303063,2.581682,0.057404,3,3,0.291260,0.896545,0.621539,2.606192,2.622762,2.516091
10,fiber_pepmorph,PVFCADQWFC,0.323134,0.029621,2.846021,0.107717,3,3,0.356060,0.298652,0.314689,2.721827,2.902227,2.914010
11,fiber_pepmorph,PVWRADSWHC,0.529067,0.047608,2.443341,0.049071,3,3,0.507244,0.496283,0.583675,2.466513,2.386975,2.476534
12,fiber_pepmorph,QIRTYDFLVF,0.687460,0.145185,2.160115,0.005033,3,3,0.817163,0.530622,0.714594,2.154567,2.161391,2.164387
13,fiber_pepmorph,RAVYGDFVFL,0.376509,0.030850,2.173862,0.024415,3,3,0.362986,0.411811,0.354731,2.176637,2.196771,2.148178
14,fiber_pepmorph,VFLVPVDFKY,0.580725,0.255395,2.789320,0.043639,3,3,0.351668,0.534394,0.856114,2.740966,2.801216,2.825777
15,sphere_pepmorph,FFIFI,0.841170,0.047626,2.835215,0.047692,3,3,0.896117,0.811735,0.815658,2.784343,2.842389,2.878914
16,sphere_pepmorph,FFLFI,0.798208,0.041528,2.727447,0.077903,3,3,0.838104,0.755220,0.801300,2.742129,2.796964,2.643248
17,sphere_pepmorph,FIFIF,0.264881,0.001356,2.339227,0.003644,3,3,0.263922,0.265839,0.819299,2.336651,2.341804,2.555382
18,sphere_pepmorph,FIFVF,0.332476,0.098749,2.355055,0.033078,3,3,0.295891,0.257241,0.444297,2.321650,2.387796,2.355720
19,sphere_pepmorph,FIVFF,0.868038,0.027635,3.071661,0.025196,3,3,0.838981,0.893988,0.871145,3.056836,3.057395,3.100753
20,sphere_pepmorph,FIVVIF,0.818963,0.091905,2.626484,0.003378,3,3,0.817350,0.911663,0.727875,2.628269,2.628596,2.622588
21,sphere_pepmorph,FLIFFI,0.779594,0.125546,2.646630,0.038847,3,3,0.634634,0.853447,0.850700,2.602607,2.661189,2.676094
22,sphere_pepmorph,FVIFF,0.873204,0.042120,3.058435,0.069404,3,3,0.866560,0.918252,0.834801,3.053138,3.130336,2.991832
23,sphere_pepmorph,FVIVI,0.825284,0.050315,2.153378,0.040481,3,3,0.847842,0.860373,0.767637,2.164393,2.187212,2.108530
24,sphere_pepmorph,IVFVI,0.755346,0.049312,2.071813,0.007323,3,3,0.703003,0.762104,0.800930,2.063410,2.075192,2.076836
25,sphere_pepmorph,IVLFIF,0.754414,0.067726,2.455844,0.048843,3,3,0.766112,0.815530,0.681601,2.407728,2.454420,2.505383
26,sphere_pepmorph,LIIVF,0.781477,0.069139,1.983241,0.052856,3,3,0.730597,0.753638,0.860195,1.949825,1.955719,2.044179
27,sphere_pepmorph,LVIIF,0.697895,0.127500,1.982113,0.042879,3,3,0.801390,0.555468,0.736827,2.006760,1.932601,2.006979
28,sphere_pepmorph,VFFIF,0.906594,0.014674,2.902559,0.029800,3,3,0.911413,0.890116,0.918253,2.870044,2.928571,2.909062
29,sphere_pepmorph,VIFIL,0.668102,0.097296,1.960551,0.033630,3,3,0.705582,0.557639,0.741084,1.924503,1.991081,1.966068

In [4]:
# load original csv
original = pd.read_csv('negative_control_structures.csv')
# rename structure_id to peptide
original = original.rename(columns={'structure_id': 'peptide'})
original

       peptide structure_type structure_id_3  ap  agg_prob  structure_length
0   EFAHHYNQIL          fiber            NaN NaN       NaN                10
1    VSVQPMECH          fiber            NaN NaN       NaN                 9
2    LYRPAPLEL          fiber            NaN NaN       NaN                 9
3     LQICQWAA          fiber            NaN NaN       NaN                 8
4     DAPFIMAY          fiber            NaN NaN       NaN                 8
..         ...            ...            ...  ..       ...               ...
82       MKFYF   unsupervised            NaN NaN       NaN                 5
83   PQVPCMGDL   unsupervised            NaN NaN       NaN                 9
84     WVWLCQG   unsupervised            NaN NaN       NaN                 7
85      YPDYSM   unsupervised            NaN NaN       NaN                 6
86  YYCDVERMIC   unsupervised            NaN NaN       NaN                10

[87 rows x 6 columns]

In [5]:
# create a column 'class'
# if structure_type='random', then class='random'
# if structure_type='unsupervised', then class='unsupervised'
# if structure_type='fiber' or 'sphere' and ap=NaN, then class='fiber_no_ap' or 'sphere_no_ap'
# if structure_type='fiber' or 'sphere' and ap!=NaN, then class='fiber_no_desc' or 'sphere_no_desc'

def classify(row):
    if row['structure_type'] == 'random':
        return 'random'
    elif row['structure_type'] == 'unsupervised':
        return 'unsupervised'
    elif row['structure_type'] == 'fiber':
        if pd.isna(row['ap']):
            return 'fiber_no_ap'
        else:
            return 'fiber_no_desc'
    elif row['structure_type'] == 'sphere':
        if pd.isna(row['ap']):
            return 'sphere_no_ap'
        else:
            return 'sphere_no_desc'
    else:
        return 'unknown'
original['class'] = original.apply(classify, axis=1)
original

,peptide,structure_type,structure_id_3,ap,agg_prob,structure_length,class
0,EFAHHYNQIL,fiber,NaN,NaN,NaN,10,fiber_no_ap
1,VSVQPMECH,fiber,NaN,NaN,NaN,9,fiber_no_ap
2,LYRPAPLEL,fiber,NaN,NaN,NaN,9,fiber_no_ap
3,LQICQWAA,fiber,NaN,NaN,NaN,8,fiber_no_ap
4,DAPFIMAY,fiber,NaN,NaN,NaN,8,fiber_no_ap
...,...,...,...,...,...,...,...
82,MKFYF,unsupervised,NaN,NaN,NaN,5,unsupervised
83,PQVPCMGDL,unsupervised,NaN,NaN,NaN,9,unsupervised
84,WVWLCQG,unsupervised,NaN,NaN,NaN,7,unsupervised
85,YPDYSM,unsupervised,NaN,NaN,NaN,6,unsupervised
86,YYCDVERMIC,unsupervised,NaN,NaN,NaN,10,unsupervised

In [6]:
original['class'].value_counts()

class
fiber_no_ap       15
sphere_no_ap      15
fiber_no_desc     15
sphere_no_desc    15
random            15
unsupervised      12
Name: count, dtype: int64

In [7]:
# merge runs and original on structure_id
merged = pd.merge(original[['peptide', 'class']], runs, on='peptide', how='left')
merged

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
0,EFAHHYNQIL,fiber_no_ap,0.563333,0.084213,1.438246,0.031033,3,3,0.660130,0.506904,0.522966,1.413070,1.428751,1.472918
1,VSVQPMECH,fiber_no_ap,0.442553,0.046878,1.377653,0.006778,3,3,0.407730,0.424076,0.495854,1.385169,1.372005,1.375784
2,LYRPAPLEL,fiber_no_ap,0.343279,0.049025,1.716276,0.017749,3,3,0.328363,0.303444,0.398030,1.725839,1.727192,1.695796
3,LQICQWAA,fiber_no_ap,0.481083,0.083499,1.831733,0.053068,3,3,0.472290,0.402329,0.568631,1.835404,1.776925,1.882870
4,DAPFIMAY,fiber_no_ap,0.612673,0.078738,1.655658,0.027332,3,3,0.632853,0.525810,0.679358,1.643816,1.636244,1.686914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,MKFYF,unsupervised,0.340749,0.053622,2.140956,0.032481,3,3,0.340139,0.394673,0.287434,2.104693,2.150798,2.167378
83,PQVPCMGDL,unsupervised,0.436468,0.051255,1.349231,0.017448,3,3,0.377295,0.465066,0.467043,1.329804,1.354323,1.363567
84,WVWLCQG,unsupervised,0.367673,0.120846,2.380745,0.053993,3,3,0.338767,0.263900,0.500350,2.426710,2.394241,2.321285
85,YPDYSM,unsupervised,0.419641,0.279942,2.004831,0.033479,3,3,0.737875,0.211401,0.309647,2.035946,2.009141,1.969406
86,YYCDVERMIC,unsupervised,0.374314,0.115319,1.878686,0.043352,3,3,0.307397,0.507472,0.308073,1.917980,1.832180,1.885899

In [8]:
runs_pepmorph.shape, merged.shape

((30, 14), (87, 14))

In [9]:
# concatenate merged and runs_pepmorph
merged = pd.concat([merged, runs_pepmorph], ignore_index=True)
merged

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
0,EFAHHYNQIL,fiber_no_ap,0.563333,0.084213,1.438246,0.031033,3,3,0.660130,0.506904,0.522966,1.413070,1.428751,1.472918
1,VSVQPMECH,fiber_no_ap,0.442553,0.046878,1.377653,0.006778,3,3,0.407730,0.424076,0.495854,1.385169,1.372005,1.375784
2,LYRPAPLEL,fiber_no_ap,0.343279,0.049025,1.716276,0.017749,3,3,0.328363,0.303444,0.398030,1.725839,1.727192,1.695796
3,LQICQWAA,fiber_no_ap,0.481083,0.083499,1.831733,0.053068,3,3,0.472290,0.402329,0.568631,1.835404,1.776925,1.882870
4,DAPFIMAY,fiber_no_ap,0.612673,0.078738,1.655658,0.027332,3,3,0.632853,0.525810,0.679358,1.643816,1.636244,1.686914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,IVLFIF,sphere_pepmorph,0.754414,0.067726,2.455844,0.048843,3,3,0.766112,0.815530,0.681601,2.407728,2.454420,2.505383
113,LIIVF,sphere_pepmorph,0.781477,0.069139,1.983241,0.052856,3,3,0.730597,0.753638,0.860195,1.949825,1.955719,2.044179
114,LVIIF,sphere_pepmorph,0.697895,0.127500,1.982113,0.042879,3,3,0.801390,0.555468,0.736827,2.006760,1.932601,2.006979
115,VFFIF,sphere_pepmorph,0.906594,0.014674,2.902559,0.029800,3,3,0.911413,0.890116,0.918253,2.870044,2.928571,2.909062
116,VIFIL,sphere_pepmorph,0.668102,0.097296,1.960551,0.033630,3,3,0.705582,0.557639,0.741084,1.924503,1.991081,1.966068

In [10]:
# get_merged by run
merged_by_run = pd.merge(original[['peptide', 'class']], by_run, on='peptide', how='left')
merged_by_run

        peptide         class    run      RMOI  aggregation_propensity
0    EFAHHYNQIL   fiber_no_ap  run_1  0.660130                1.413070
1    EFAHHYNQIL   fiber_no_ap  run_2  0.506904                1.428751
2    EFAHHYNQIL   fiber_no_ap  run_3  0.522966                1.472918
3     VSVQPMECH   fiber_no_ap  run_1  0.407730                1.385169
4     VSVQPMECH   fiber_no_ap  run_2  0.424076                1.372005
..          ...           ...    ...       ...                     ...
256      YPDYSM  unsupervised  run_2  0.211401                2.009141
257      YPDYSM  unsupervised  run_3  0.309647                1.969406
258  YYCDVERMIC  unsupervised  run_1  0.307397                1.917980
259  YYCDVERMIC  unsupervised  run_2  0.507472                1.832180
260  YYCDVERMIC  unsupervised  run_3  0.308073                1.885899

[261 rows x 5 columns]

In [11]:
# concatenate merged_by_run and by_run_pepmorph
merged_by_run = pd.concat([merged_by_run, by_run_pepmorph], ignore_index=True)
merged_by_run

,peptide,class,run,RMOI,aggregation_propensity,visual_morphology,is_target
0,EFAHHYNQIL,fiber_no_ap,run_1,0.660130,1.413070,NaN,NaN
1,EFAHHYNQIL,fiber_no_ap,run_2,0.506904,1.428751,NaN,NaN
2,EFAHHYNQIL,fiber_no_ap,run_3,0.522966,1.472918,NaN,NaN
3,VSVQPMECH,fiber_no_ap,run_1,0.407730,1.385169,NaN,NaN
4,VSVQPMECH,fiber_no_ap,run_2,0.424076,1.372005,NaN,NaN
...,...,...,...,...,...,...,...
346,RAVYGDFVFL,fiber_pepmorph,run_2,0.411811,2.196771,sheet string-like,no
347,RAVYGDFVFL,fiber_pepmorph,run_3,0.354731,2.148178,fiber intertwined,yes
348,VFLVPVDFKY,fiber_pepmorph,run_1,0.351668,2.740966,fiber,yes
349,VFLVPVDFKY,fiber_pepmorph,run_2,0.534394,2.801216,vesicle,no
350,VFLVPVDFKY,fiber_pepmorph,run_3,0.856114,2.825777,vesicle,no

In [12]:
merged['class'].value_counts()

class
fiber_no_ap        15
sphere_no_ap       15
fiber_no_desc      15
sphere_no_desc     15
random             15
fiber_pepmorph     15
sphere_pepmorph    15
unsupervised       12
Name: count, dtype: int64

In [13]:
# show merged with class='random'
merged_random = merged[merged['class'] == 'random']
print('Length of merged_random:', len(merged_random))
merged_random

Length of merged_random: 15

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
60,MEIDC,random,0.763299,0.034073,1.046173,0.002050,3,3,0.761112,0.730371,0.798412,1.044081,1.048177,1.046261
61,NGCAN,random,0.563696,0.171687,1.052546,0.001169,3,3,0.474494,0.454973,0.761622,1.051729,1.053886,1.052024
62,NTLSRR,random,0.804962,0.008248,1.080805,0.005867,3,3,0.808411,0.795550,0.810926,1.084671,1.074054,1.083689
63,WNYDFW,random,0.493801,0.112435,2.700536,0.060082,3,3,0.430901,0.426891,0.623609,2.711947,2.635566,2.754094
64,HKHVEQV,random,0.386024,0.051409,1.469097,0.014670,3,3,0.445144,0.351825,0.361103,1.452614,1.480721,1.473956
65,KCYRHNI,random,0.490656,0.046451,1.298515,0.014879,3,3,0.469547,0.543912,0.458508,1.287652,1.315474,1.292417
66,RDQTEVIE,random,0.646534,0.072908,1.198276,0.009263,3,3,0.571131,0.651811,0.716661,1.208843,1.194426,1.191560
67,CGLEVNCL,random,0.845331,0.093763,1.098466,0.025305,3,3,0.747024,0.855199,0.933770,1.121048,1.103234,1.071115
68,EQSRIQISP,random,0.831973,0.066681,1.136775,0.021615,3,3,0.798476,0.788681,0.908761,1.153397,1.144588,1.112340
69,VRPKRPAHK,random,0.906012,0.025405,1.066658,0.002574,3,3,0.917691,0.923477,0.876868,1.064436,1.066060,1.069479
70,ANIMWTIDDA,random,0.653338,0.189522,1.673403,0.370538,3,3,0.565503,0.523668,0.870842,1.850624,1.922050,1.247535
71,FLHKHKINCA,random,0.555753,0.007414,1.440051,0.007297,3,3,0.550353,0.552700,0.564205,1.431722,1.443113,1.445317
72,RMIHWMME,random,0.421080,0.083777,2.388129,0.051631,3,3,0.508961,0.342121,0.412157,2.443020,2.340534,2.380835
73,CNGCANN,random,0.806708,0.072587,1.085146,0.005522,3,3,0.740988,0.794519,0.884618,1.087174,1.078897,1.089368
74,TLSRR,random,0.789222,0.135237,1.057063,0.006906,3,3,0.831512,0.898261,0.637894,1.060561,1.049108,1.061519

In [14]:
# show peptides with AP >= 1.8
print(f'Random Peptides with aggregation_propensity_mean >= 1.8: {len(merged_random[merged_random["aggregation_propensity_mean"] >= 1.8])}')
merged_random[merged_random['aggregation_propensity_mean'] >= 1.8]

Random Peptides with aggregation_propensity_mean >= 1.8: 2

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
63,WNYDFW,random,0.493801,0.112435,2.700536,0.060082,3,3,0.430901,0.426891,0.623609,2.711947,2.635566,2.754094
72,RMIHWMME,random,0.421080,0.083777,2.388129,0.051631,3,3,0.508961,0.342121,0.412157,2.443020,2.340534,2.380835

In [15]:
# show peptides with AP >- 1.8 by run with majority vote
merged_random_by_run = merged_by_run[merged_by_run['class'] == 'random']
print(f'Random Peptides by run with aggregation_propensity >= 1.8 in majority of runs: {len(merged_random_by_run[merged_random_by_run["aggregation_propensity"] >= 1.8])}')
merged_random_by_run_majority = merged_random_by_run.groupby('peptide').agg(
    majority_ap=('aggregation_propensity', lambda x: (x >= 1.8).sum() > (len(x) / 2))
).reset_index()
merged_random_by_run_majority = merged_random_by_run_majority[merged_random_by_run_majority['majority_ap']]
merged_random_by_run_majority

Random Peptides by run with aggregation_propensity >= 1.8 in majority of runs: 8

       peptide  majority_ap
0   ANIMWTIDDA         True
11    RMIHWMME         True
14      WNYDFW         True

In [16]:
# show merged with class='unsupervised'
merged_unsupervised = merged[merged['class'] == 'unsupervised']
print('Length of merged_unsupervised:', len(merged_unsupervised))
merged_unsupervised

Length of merged_unsupervised: 12

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
75,CIKYEHT,unsupervised,0.568490,0.075989,1.820543,0.019709,3,3,0.631853,0.484243,0.589373,1.842257,1.803784,1.815589
76,CYVIMIVLRK,unsupervised,0.704004,0.080684,1.290151,0.024463,3,3,0.749498,0.610846,0.751667,1.262078,1.301472,1.306902
77,EWKNE,unsupervised,0.574010,0.099007,1.573135,0.011585,3,3,0.685785,0.497331,0.538913,1.560122,1.582324,1.576961
78,FCIICHDPD,unsupervised,0.372138,0.048744,1.661720,0.002951,3,3,0.351677,0.336960,0.427777,1.664795,1.658910,1.661456
79,GLPCCNRS,unsupervised,0.805560,0.070769,1.153883,0.012585,3,3,0.725068,0.858015,0.833596,1.142006,1.167073,1.152570
80,ILFWYP,unsupervised,0.855180,0.019672,3.093685,0.087354,3,3,0.839153,0.877134,0.849253,3.005708,3.094945,3.180402
81,MADRKTWY,unsupervised,0.470531,0.151662,1.909269,0.025737,3,3,0.632692,0.446714,0.332187,1.893977,1.894847,1.938984
82,MKFYF,unsupervised,0.340749,0.053622,2.140956,0.032481,3,3,0.340139,0.394673,0.287434,2.104693,2.150798,2.167378
83,PQVPCMGDL,unsupervised,0.436468,0.051255,1.349231,0.017448,3,3,0.377295,0.465066,0.467043,1.329804,1.354323,1.363567
84,WVWLCQG,unsupervised,0.367673,0.120846,2.380745,0.053993,3,3,0.338767,0.263900,0.500350,2.426710,2.394241,2.321285
85,YPDYSM,unsupervised,0.419641,0.279942,2.004831,0.033479,3,3,0.737875,0.211401,0.309647,2.035946,2.009141,1.969406
86,YYCDVERMIC,unsupervised,0.374314,0.115319,1.878686,0.043352,3,3,0.307397,0.507472,0.308073,1.917980,1.832180,1.885899

In [17]:
# show peptides with AP >= 1.8
print(f'Unsupervised Peptides with aggregation_propensity_mean >= 1.8: {len(merged_unsupervised[merged_unsupervised["aggregation_propensity_mean"] >= 1.8])}')
merged_unsupervised[merged_unsupervised['aggregation_propensity_mean'] >= 1.8]

Unsupervised Peptides with aggregation_propensity_mean >= 1.8: 7

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
75,CIKYEHT,unsupervised,0.568490,0.075989,1.820543,0.019709,3,3,0.631853,0.484243,0.589373,1.842257,1.803784,1.815589
80,ILFWYP,unsupervised,0.855180,0.019672,3.093685,0.087354,3,3,0.839153,0.877134,0.849253,3.005708,3.094945,3.180402
81,MADRKTWY,unsupervised,0.470531,0.151662,1.909269,0.025737,3,3,0.632692,0.446714,0.332187,1.893977,1.894847,1.938984
82,MKFYF,unsupervised,0.340749,0.053622,2.140956,0.032481,3,3,0.340139,0.394673,0.287434,2.104693,2.150798,2.167378
84,WVWLCQG,unsupervised,0.367673,0.120846,2.380745,0.053993,3,3,0.338767,0.263900,0.500350,2.426710,2.394241,2.321285
85,YPDYSM,unsupervised,0.419641,0.279942,2.004831,0.033479,3,3,0.737875,0.211401,0.309647,2.035946,2.009141,1.969406
86,YYCDVERMIC,unsupervised,0.374314,0.115319,1.878686,0.043352,3,3,0.307397,0.507472,0.308073,1.917980,1.832180,1.885899

In [18]:
# show peptides with AP >- 1.8 by run with majority vote
merged_unsupervised_by_run = merged_by_run[merged_by_run['class'] == 'unsupervised']
print(f'Unsupervised Peptides by run with aggregation_propensity >= 1.8 in majority of runs: {len(merged_unsupervised_by_run[merged_unsupervised_by_run["aggregation_propensity"] >= 1.8])}')
merged_unsupervised_by_run_majority = merged_unsupervised_by_run.groupby('peptide').agg(
    majority_ap=('aggregation_propensity', lambda x: (x >= 1.8).sum() > (len(x) / 2))
).reset_index()
merged_unsupervised_by_run_majority = merged_unsupervised_by_run_majority[merged_unsupervised_by_run_majority['majority_ap']]
merged_unsupervised_by_run_majority

Unsupervised Peptides by run with aggregation_propensity >= 1.8 in majority of runs: 21

       peptide  majority_ap
0      CIKYEHT         True
5       ILFWYP         True
6     MADRKTWY         True
7        MKFYF         True
9      WVWLCQG         True
10      YPDYSM         True
11  YYCDVERMIC         True

In [19]:
# show merged with class='fiber_no_ap'
merged_fiber_no_ap = merged[merged['class'] == 'fiber_no_ap']
print('Length of merged_fiber_no_ap:', len(merged_fiber_no_ap))
merged_fiber_no_ap

Length of merged_fiber_no_ap: 15

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
0,EFAHHYNQIL,fiber_no_ap,0.563333,0.084213,1.438246,0.031033,3,3,0.660130,0.506904,0.522966,1.413070,1.428751,1.472918
1,VSVQPMECH,fiber_no_ap,0.442553,0.046878,1.377653,0.006778,3,3,0.407730,0.424076,0.495854,1.385169,1.372005,1.375784
2,LYRPAPLEL,fiber_no_ap,0.343279,0.049025,1.716276,0.017749,3,3,0.328363,0.303444,0.398030,1.725839,1.727192,1.695796
3,LQICQWAA,fiber_no_ap,0.481083,0.083499,1.831733,0.053068,3,3,0.472290,0.402329,0.568631,1.835404,1.776925,1.882870
4,DAPFIMAY,fiber_no_ap,0.612673,0.078738,1.655658,0.027332,3,3,0.632853,0.525810,0.679358,1.643816,1.636244,1.686914
5,LCPDSILVN,fiber_no_ap,0.831906,0.047882,1.111086,0.010236,3,3,0.886631,0.797719,0.811368,1.099380,1.115523,1.118354
6,GPCIDQCSF,fiber_no_ap,0.455975,0.132881,1.602069,0.036431,3,3,0.346070,0.603653,0.418202,1.642062,1.593371,1.570775
7,HALNGGTW,fiber_no_ap,0.410053,0.127840,1.813806,0.016524,3,3,0.351440,0.556691,0.322029,1.810493,1.799189,1.831736
8,VYHEIDGFK,fiber_no_ap,0.388311,0.064073,1.560331,0.010116,3,3,0.335075,0.370435,0.459424,1.569399,1.549420,1.562175
9,AWIRYDE,fiber_no_ap,0.492994,0.121244,2.056279,0.025024,3,3,0.632445,0.433991,0.412544,2.071116,2.070333,2.027387
10,PEPFLNKTVM,fiber_no_ap,0.489096,0.046024,1.562164,0.004038,3,3,0.473804,0.452664,0.540820,1.565555,1.563240,1.557698
11,EVLLAHAW,fiber_no_ap,0.712450,0.098479,1.388111,0.037749,3,3,0.825569,0.665952,0.645827,1.424575,1.349197,1.390561
12,QVLGQWSLP,fiber_no_ap,0.587155,0.030343,1.718172,0.026368,3,3,0.621654,0.564604,0.575207,1.699732,1.706410,1.748374
13,KTKEWHHE,fiber_no_ap,0.424822,0.052233,2.226057,0.016374,3,3,0.381237,0.410510,0.482719,2.230609,2.207889,2.239674
14,KVLGDNPW,fiber_no_ap,0.428899,0.057935,1.757433,0.031327,3,3,0.483200,0.435585,0.367911,1.754801,1.789994,1.727505

In [20]:
# show peptides with AP >= 1.8
print(f'Fiber_no_ap Peptides with aggregation_propensity_mean >= 1.8: {len(merged_fiber_no_ap[merged_fiber_no_ap["aggregation_propensity_mean"] >= 1.8])}')
merged_fiber_no_ap[merged_fiber_no_ap['aggregation_propensity_mean'] >= 1.8]

Fiber_no_ap Peptides with aggregation_propensity_mean >= 1.8: 4

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
3,LQICQWAA,fiber_no_ap,0.481083,0.083499,1.831733,0.053068,3,3,0.472290,0.402329,0.568631,1.835404,1.776925,1.882870
7,HALNGGTW,fiber_no_ap,0.410053,0.127840,1.813806,0.016524,3,3,0.351440,0.556691,0.322029,1.810493,1.799189,1.831736
9,AWIRYDE,fiber_no_ap,0.492994,0.121244,2.056279,0.025024,3,3,0.632445,0.433991,0.412544,2.071116,2.070333,2.027387
13,KTKEWHHE,fiber_no_ap,0.424822,0.052233,2.226057,0.016374,3,3,0.381237,0.410510,0.482719,2.230609,2.207889,2.239674

In [21]:
# show peptides with AP >- 1.8 by run with majority vote
merged_fiber_no_ap_by_run = merged_by_run[merged_by_run['class'] == 'fiber_no_ap']
print(f'Fiber_no_ap Peptides by run with aggregation_propensity >= 1.8 in majority of runs: {len(merged_fiber_no_ap_by_run[merged_fiber_no_ap_by_run["aggregation_propensity"] >= 1.8])}')
merged_fiber_no_ap_by_run_majority = merged_fiber_no_ap_by_run.groupby('peptide').agg(
    majority_ap=('aggregation_propensity', lambda x: (x >= 1.8).sum() > (len(x) / 2))
).reset_index()
merged_fiber_no_ap_by_run_majority = merged_fiber_no_ap_by_run_majority[merged_fiber_no_ap_by_run_majority['majority_ap']]
merged_fiber_no_ap_by_run_majority

Fiber_no_ap Peptides by run with aggregation_propensity >= 1.8 in majority of runs: 10

    peptide  majority_ap
0   AWIRYDE         True
5  HALNGGTW         True
6  KTKEWHHE         True
9  LQICQWAA         True

In [22]:
# show merged with class='sphere_no_ap'
merged_sphere_no_ap = merged[merged['class'] == 'sphere_no_ap']
print('Length of merged_sphere_no_ap:', len(merged_sphere_no_ap))
merged_sphere_no_ap

Length of merged_sphere_no_ap: 15

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
15,ERIRED,sphere_no_ap,0.781964,0.047416,1.107696,0.005130,3,3,0.769607,0.834335,0.741950,1.111235,1.110042,1.101813
16,VCDVI,sphere_no_ap,0.802133,0.045522,1.060584,0.000371,3,3,0.837241,0.818458,0.750699,1.060793,1.060156,1.060805
17,CEESFR,sphere_no_ap,0.833369,0.033420,1.104380,0.019890,3,3,0.796793,0.862311,0.841003,1.082543,1.109137,1.121459
18,VEMASH,sphere_no_ap,0.826142,0.056316,1.098576,0.006153,3,3,0.764567,0.838826,0.875035,1.099808,1.104019,1.091901
19,LFRQEE,sphere_no_ap,0.452697,0.093304,1.304693,0.009184,3,3,0.560419,0.397251,0.400421,1.301173,1.315116,1.297791
20,REMNSFE,sphere_no_ap,0.437169,0.058857,1.678879,0.014039,3,3,0.405145,0.401267,0.505094,1.663098,1.689982,1.683557
21,VEFAV,sphere_no_ap,0.427171,0.115045,1.436321,0.031086,3,3,0.339183,0.384974,0.557357,1.400901,1.459070,1.448993
22,MIVDCVL,sphere_no_ap,0.727815,0.084995,1.147361,0.007846,3,3,0.714003,0.650571,0.818870,1.147927,1.154908,1.139247
23,PLVEILG,sphere_no_ap,0.838594,0.032910,1.076319,0.005080,3,3,0.869096,0.842973,0.803715,1.081546,1.071401,1.076012
24,ERWDK,sphere_no_ap,0.577231,0.045686,1.617049,0.012577,3,3,0.544904,0.629497,0.557292,1.605017,1.630107,1.616022
25,QWHECK,sphere_no_ap,0.402932,0.091541,1.990880,0.025172,3,3,0.301812,0.480153,0.426831,2.005960,2.004860,1.961821
26,IRDYKE,sphere_no_ap,0.440932,0.053752,1.302402,0.010285,3,3,0.498503,0.432233,0.392061,1.304871,1.291107,1.311227
27,FAETV,sphere_no_ap,0.512143,0.113647,1.266115,0.033972,3,3,0.387013,0.540467,0.608949,1.262993,1.233812,1.301540
28,VMAIVIE,sphere_no_ap,0.452041,0.156543,1.371206,0.003182,3,3,0.616512,0.434752,0.304861,1.369685,1.374863,1.369068
29,RKEPIE,sphere_no_ap,0.463386,0.054679,1.243960,0.006787,3,3,0.514009,0.470751,0.405398,1.249139,1.246464,1.236277

In [23]:
# show peptides with AP >= 1.8
print(f'Sphere_no_ap Peptides with aggregation_propensity_mean >= 1.8: {len(merged_sphere_no_ap[merged_sphere_no_ap["aggregation_propensity_mean"] >= 1.8])}')
merged_sphere_no_ap[merged_sphere_no_ap['aggregation_propensity_mean'] >= 1.8]

Sphere_no_ap Peptides with aggregation_propensity_mean >= 1.8: 1

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
25,QWHECK,sphere_no_ap,0.402932,0.091541,1.99088,0.025172,3,3,0.301812,0.480153,0.426831,2.00596,2.00486,1.961821

In [24]:
# show peptides with AP >- 1.8 by run with majority vote
merged_sphere_no_ap_by_run = merged_by_run[merged_by_run['class'] == 'sphere_no_ap']
print(f'Sphere_no_ap Peptides by run with aggregation_propensity >= 1.8 in majority of runs: {len(merged_sphere_no_ap_by_run[merged_sphere_no_ap_by_run["aggregation_propensity"] >= 1.8])}')
merged_sphere_no_ap_by_run_majority = merged_sphere_no_ap_by_run.groupby('peptide').agg(
    majority_ap=('aggregation_propensity', lambda x: (x >= 1.8).sum() > (len(x) / 2))
).reset_index()
merged_sphere_no_ap_by_run_majority = merged_sphere_no_ap_by_run_majority[merged_sphere_no_ap_by_run_majority['majority_ap']]
merged_sphere_no_ap_by_run_majority

Sphere_no_ap Peptides by run with aggregation_propensity >= 1.8 in majority of runs: 3

  peptide  majority_ap
8  QWHECK         True

In [25]:
# show merged with class='fiber_no_desc'
merged_fiber_no_desc = merged[merged['class'] == 'fiber_no_desc']
print('Length of merged_fiber_no_desc:', len(merged_fiber_no_desc))
merged_fiber_no_desc

Length of merged_fiber_no_desc: 15

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
30,PNVVYQVWYT,fiber_no_desc,0.388180,0.081184,2.506343,0.037630,3,3,0.334895,0.481616,0.348029,2.549334,2.479385,2.490310
31,IFCLIRSYLM,fiber_no_desc,0.442832,0.110259,1.943411,0.030072,3,3,0.315520,0.507449,0.505526,1.965083,1.956072,1.909079
32,RLSHNAMLY,fiber_no_desc,0.332462,0.014049,1.722893,0.037711,3,3,0.336337,0.344167,0.316883,1.697040,1.705475,1.766166
33,WEFTGVNFT,fiber_no_desc,0.539255,0.097904,2.208991,0.020505,3,3,0.648432,0.510069,0.459263,2.230452,2.189599,2.206922
34,LEYGFYCV,fiber_no_desc,0.463419,0.155541,2.170786,0.010177,3,3,0.637675,0.338623,0.413958,2.174837,2.159206,2.178313
35,FVHIVNDQVV,fiber_no_desc,0.521236,0.092739,1.551053,0.027062,3,3,0.543369,0.419433,0.600905,1.549136,1.579023,1.525001
36,PPFAQPMW,fiber_no_desc,0.804766,0.052645,2.810548,0.028768,3,3,0.807107,0.750990,0.856201,2.786253,2.803076,2.842316
37,LFLIACTPY,fiber_no_desc,0.524480,0.268550,2.503452,0.024925,3,3,0.794354,0.257273,0.521813,2.479741,2.529435,2.501179
38,WRWSDGCIL,fiber_no_desc,0.434684,0.052369,2.255612,0.020766,3,3,0.402403,0.495107,0.406542,2.273810,2.232991,2.260033
39,VFESFTPY,fiber_no_desc,0.282353,0.043487,2.220946,0.049071,3,3,0.252264,0.332213,0.262582,2.227484,2.266419,2.168933
40,TLAGIRWVTE,fiber_no_desc,0.435568,0.112237,2.058011,0.037149,3,3,0.305981,0.498788,0.501935,2.097157,2.023248,2.053629
41,PFVCLIVF,fiber_no_desc,0.805776,0.093200,2.770981,0.019851,3,3,0.829716,0.702942,0.884671,2.748812,2.777021,2.787110
42,FIRSESFL,fiber_no_desc,0.351789,0.098477,1.961227,0.034714,3,3,0.304544,0.285837,0.464986,1.975259,1.986728,1.921694
43,PVFVIVVFP,fiber_no_desc,0.799396,0.076102,2.766259,0.020776,3,3,0.711534,0.844614,0.842039,2.745925,2.765400,2.787452
44,FPVSYAIY,fiber_no_desc,0.756956,0.025675,2.930780,0.062025,3,3,0.757536,0.730996,0.782336,2.888661,2.901672,3.002005

In [26]:
# SHOW peptides with AP >= 1.8
print(f'Fiber_no_desc Peptides with aggregation_propensity_mean >= 1.8: {len(merged_fiber_no_desc[merged_fiber_no_desc["aggregation_propensity_mean"] >= 1.8])}')
merged_fiber_no_desc[merged_fiber_no_desc['aggregation_propensity_mean'] >= 1.8]

Fiber_no_desc Peptides with aggregation_propensity_mean >= 1.8: 13

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
30,PNVVYQVWYT,fiber_no_desc,0.388180,0.081184,2.506343,0.037630,3,3,0.334895,0.481616,0.348029,2.549334,2.479385,2.490310
31,IFCLIRSYLM,fiber_no_desc,0.442832,0.110259,1.943411,0.030072,3,3,0.315520,0.507449,0.505526,1.965083,1.956072,1.909079
33,WEFTGVNFT,fiber_no_desc,0.539255,0.097904,2.208991,0.020505,3,3,0.648432,0.510069,0.459263,2.230452,2.189599,2.206922
34,LEYGFYCV,fiber_no_desc,0.463419,0.155541,2.170786,0.010177,3,3,0.637675,0.338623,0.413958,2.174837,2.159206,2.178313
36,PPFAQPMW,fiber_no_desc,0.804766,0.052645,2.810548,0.028768,3,3,0.807107,0.750990,0.856201,2.786253,2.803076,2.842316
37,LFLIACTPY,fiber_no_desc,0.524480,0.268550,2.503452,0.024925,3,3,0.794354,0.257273,0.521813,2.479741,2.529435,2.501179
38,WRWSDGCIL,fiber_no_desc,0.434684,0.052369,2.255612,0.020766,3,3,0.402403,0.495107,0.406542,2.273810,2.232991,2.260033
39,VFESFTPY,fiber_no_desc,0.282353,0.043487,2.220946,0.049071,3,3,0.252264,0.332213,0.262582,2.227484,2.266419,2.168933
40,TLAGIRWVTE,fiber_no_desc,0.435568,0.112237,2.058011,0.037149,3,3,0.305981,0.498788,0.501935,2.097157,2.023248,2.053629
41,PFVCLIVF,fiber_no_desc,0.805776,0.093200,2.770981,0.019851,3,3,0.829716,0.702942,0.884671,2.748812,2.777021,2.787110
42,FIRSESFL,fiber_no_desc,0.351789,0.098477,1.961227,0.034714,3,3,0.304544,0.285837,0.464986,1.975259,1.986728,1.921694
43,PVFVIVVFP,fiber_no_desc,0.799396,0.076102,2.766259,0.020776,3,3,0.711534,0.844614,0.842039,2.745925,2.765400,2.787452
44,FPVSYAIY,fiber_no_desc,0.756956,0.025675,2.930780,0.062025,3,3,0.757536,0.730996,0.782336,2.888661,2.901672,3.002005

In [27]:
# show peptides with AP >- 1.8 by run with majority vote
merged_fiber_no_desc_by_run = merged_by_run[merged_by_run['class'] == 'fiber_no_desc']
print(f'Fiber_no_desc Peptides by run with aggregation_propensity >= 1.8 in majority of runs: {len(merged_fiber_no_desc_by_run[merged_fiber_no_desc_by_run["aggregation_propensity"] >= 1.8])}')
merged_fiber_no_desc_by_run_majority = merged_fiber_no_desc_by_run.groupby('peptide').agg(
    majority_ap=('aggregation_propensity', lambda x: (x >= 1.8).sum() > (len(x) / 2))
).reset_index()
merged_fiber_no_desc_by_run_majority = merged_fiber_no_desc_by_run_majority[merged_fiber_no_desc_by_run_majority['majority_ap']]
print(f'Fiber_no_desc Peptides by run with aggregation_propensity >= 1.8 in majority of runs: {len(merged_fiber_no_desc_by_run_majority)}')
merged_fiber_no_desc_by_run_majority

Fiber_no_desc Peptides by run with aggregation_propensity >= 1.8 in majority of runs: 39
Fiber_no_desc Peptides by run with aggregation_propensity >= 1.8 in majority of runs: 13

       peptide  majority_ap
0     FIRSESFL         True
1     FPVSYAIY         True
3   IFCLIRSYLM         True
4     LEYGFYCV         True
5    LFLIACTPY         True
6     PFVCLIVF         True
7   PNVVYQVWYT         True
8     PPFAQPMW         True
9    PVFVIVVFP         True
11  TLAGIRWVTE         True
12    VFESFTPY         True
13   WEFTGVNFT         True
14   WRWSDGCIL         True

In [28]:
# show merged with class='sphere_no_desc'
merged_sphere_no_desc = merged[merged['class'] == 'sphere_no_desc']
print('Length of merged_sphere_no_desc:', len(merged_sphere_no_desc))
merged_sphere_no_desc

Length of merged_sphere_no_desc: 15

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
45,VIFDF,sphere_no_desc,0.528324,0.124981,1.834714,0.008264,3,3,0.672120,0.467025,0.445827,1.843829,1.832599,1.827713
46,WWVWE,sphere_no_desc,0.379367,0.083541,2.769770,0.020897,3,3,0.366098,0.303254,0.468748,2.783618,2.745732,2.779959
47,WFFWFW,sphere_no_desc,0.641295,0.349341,3.970156,0.038951,3,3,0.238996,0.868053,0.816837,3.925246,3.994720,3.990504
48,CFMVAVF,sphere_no_desc,0.878688,0.011373,2.985407,0.042653,3,3,0.871235,0.891779,0.873051,2.936173,3.008888,3.011160
49,WAVFGVD,sphere_no_desc,0.389549,0.153028,2.489687,0.069016,3,3,0.229995,0.403566,0.535087,2.519295,2.410806,2.538959
50,FYFIL,sphere_no_desc,0.879656,0.011718,2.817054,0.046366,3,3,0.879624,0.891390,0.867955,2.825264,2.858767,2.767132
51,WAIEF,sphere_no_desc,0.550011,0.104368,2.242184,0.011185,3,3,0.558499,0.649876,0.441659,2.253919,2.231646,2.240988
52,LFLCLYV,sphere_no_desc,0.682022,0.368590,2.630911,0.053823,3,3,0.258750,0.855066,0.932250,2.570867,2.647046,2.674822
53,CHGLICA,sphere_no_desc,0.836299,0.032412,1.142243,0.017424,3,3,0.860634,0.799507,0.848756,1.138605,1.161199,1.126924
54,LFVILP,sphere_no_desc,0.710997,0.162759,2.036723,0.046104,3,3,0.872758,0.547257,0.712976,2.083819,1.991678,2.034672
55,FACWV,sphere_no_desc,0.657966,0.362719,2.892048,0.969424,3,3,0.879836,0.854676,0.239386,3.472778,3.430446,1.772920
56,CMLWM,sphere_no_desc,0.512664,0.319661,2.190636,0.601776,3,3,0.741998,0.648471,0.147522,2.522110,2.553792,1.496005
57,VLWYIWI,sphere_no_desc,0.314484,0.157063,3.147345,0.009458,3,3,0.214046,0.233924,0.495480,3.136479,3.153736,3.151819
58,WMAHA,sphere_no_desc,0.856663,0.039243,2.962366,0.095058,3,3,0.849396,0.821562,0.899031,2.868542,2.959944,3.058611
59,LVIEFF,sphere_no_desc,0.340407,0.115152,1.786453,0.022040,3,3,0.232692,0.326750,0.461779,1.798510,1.799834,1.761015

In [29]:
# show peptides with AP >= 1.8
print(f'Sphere_no_desc Peptides with aggregation_propensity_mean >= 1.8: {len(merged_sphere_no_desc[merged_sphere_no_desc["aggregation_propensity_mean"] >= 1.8])}')
merged_sphere_no_desc[merged_sphere_no_desc['aggregation_propensity_mean'] >= 1.8]

Sphere_no_desc Peptides with aggregation_propensity_mean >= 1.8: 13

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
45,VIFDF,sphere_no_desc,0.528324,0.124981,1.834714,0.008264,3,3,0.672120,0.467025,0.445827,1.843829,1.832599,1.827713
46,WWVWE,sphere_no_desc,0.379367,0.083541,2.769770,0.020897,3,3,0.366098,0.303254,0.468748,2.783618,2.745732,2.779959
47,WFFWFW,sphere_no_desc,0.641295,0.349341,3.970156,0.038951,3,3,0.238996,0.868053,0.816837,3.925246,3.994720,3.990504
48,CFMVAVF,sphere_no_desc,0.878688,0.011373,2.985407,0.042653,3,3,0.871235,0.891779,0.873051,2.936173,3.008888,3.011160
49,WAVFGVD,sphere_no_desc,0.389549,0.153028,2.489687,0.069016,3,3,0.229995,0.403566,0.535087,2.519295,2.410806,2.538959
50,FYFIL,sphere_no_desc,0.879656,0.011718,2.817054,0.046366,3,3,0.879624,0.891390,0.867955,2.825264,2.858767,2.767132
51,WAIEF,sphere_no_desc,0.550011,0.104368,2.242184,0.011185,3,3,0.558499,0.649876,0.441659,2.253919,2.231646,2.240988
52,LFLCLYV,sphere_no_desc,0.682022,0.368590,2.630911,0.053823,3,3,0.258750,0.855066,0.932250,2.570867,2.647046,2.674822
54,LFVILP,sphere_no_desc,0.710997,0.162759,2.036723,0.046104,3,3,0.872758,0.547257,0.712976,2.083819,1.991678,2.034672
55,FACWV,sphere_no_desc,0.657966,0.362719,2.892048,0.969424,3,3,0.879836,0.854676,0.239386,3.472778,3.430446,1.772920
56,CMLWM,sphere_no_desc,0.512664,0.319661,2.190636,0.601776,3,3,0.741998,0.648471,0.147522,2.522110,2.553792,1.496005
57,VLWYIWI,sphere_no_desc,0.314484,0.157063,3.147345,0.009458,3,3,0.214046,0.233924,0.495480,3.136479,3.153736,3.151819
58,WMAHA,sphere_no_desc,0.856663,0.039243,2.962366,0.095058,3,3,0.849396,0.821562,0.899031,2.868542,2.959944,3.058611

In [30]:
# show peptides with AP >- 1.8 by run with majority vote
merged_sphere_no_desc_by_run = merged_by_run[merged_by_run['class'] == 'sphere_no_desc']
print(f'Sphere_no_desc Peptides by run with aggregation_propensity >= 1.8 in majority of runs: {len(merged_sphere_no_desc_by_run[merged_sphere_no_desc_by_run["aggregation_propensity"] >= 1.8])}')
merged_sphere_no_desc_by_run_majority = merged_sphere_no_desc_by_run.groupby('peptide').agg(
    majority_ap=('aggregation_propensity', lambda x: (x >= 1.8).sum() > (len(x) / 2))
).reset_index()
merged_sphere_no_desc_by_run_majority = merged_sphere_no_desc_by_run_majority[merged_sphere_no_desc_by_run_majority['majority_ap']]
print(f'Length of merged_sphere_no_desc_by_run_majority:', len(merged_sphere_no_desc_by_run_majority))
merged_sphere_no_desc_by_run_majority

Sphere_no_desc Peptides by run with aggregation_propensity >= 1.8 in majority of runs: 37
Length of merged_sphere_no_desc_by_run_majority: 13

    peptide  majority_ap
0   CFMVAVF         True
2     CMLWM         True
3     FACWV         True
4     FYFIL         True
5   LFLCLYV         True
6    LFVILP         True
8     VIFDF         True
9   VLWYIWI         True
10    WAIEF         True
11  WAVFGVD         True
12   WFFWFW         True
13    WMAHA         True
14    WWVWE         True

In [31]:
# show merged with class='sphere_pepmorph'
merged_sphere_pepmorph = merged[merged['class'] == 'sphere_pepmorph']
print('Length of merged_sphere_pepmorph:', len(merged_sphere_pepmorph))

Length of merged_sphere_pepmorph: 15

In [32]:
# show peptides with AP >= 1.8
print(f'Sphere_pepmorph Peptides with aggregation_propensity_mean >= 1.8: {len(merged_sphere_pepmorph[merged_sphere_pepmorph["aggregation_propensity_mean"] >= 1.8])}')
merged_sphere_pepmorph[merged_sphere_pepmorph['aggregation_propensity_mean'] >= 1.8]

Sphere_pepmorph Peptides with aggregation_propensity_mean >= 1.8: 15

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
102,FFIFI,sphere_pepmorph,0.841170,0.047626,2.835215,0.047692,3,3,0.896117,0.811735,0.815658,2.784343,2.842389,2.878914
103,FFLFI,sphere_pepmorph,0.798208,0.041528,2.727447,0.077903,3,3,0.838104,0.755220,0.801300,2.742129,2.796964,2.643248
104,FIFIF,sphere_pepmorph,0.264881,0.001356,2.339227,0.003644,3,3,0.263922,0.265839,0.819299,2.336651,2.341804,2.555382
105,FIFVF,sphere_pepmorph,0.332476,0.098749,2.355055,0.033078,3,3,0.295891,0.257241,0.444297,2.321650,2.387796,2.355720
106,FIVFF,sphere_pepmorph,0.868038,0.027635,3.071661,0.025196,3,3,0.838981,0.893988,0.871145,3.056836,3.057395,3.100753
107,FIVVIF,sphere_pepmorph,0.818963,0.091905,2.626484,0.003378,3,3,0.817350,0.911663,0.727875,2.628269,2.628596,2.622588
108,FLIFFI,sphere_pepmorph,0.779594,0.125546,2.646630,0.038847,3,3,0.634634,0.853447,0.850700,2.602607,2.661189,2.676094
109,FVIFF,sphere_pepmorph,0.873204,0.042120,3.058435,0.069404,3,3,0.866560,0.918252,0.834801,3.053138,3.130336,2.991832
110,FVIVI,sphere_pepmorph,0.825284,0.050315,2.153378,0.040481,3,3,0.847842,0.860373,0.767637,2.164393,2.187212,2.108530
111,IVFVI,sphere_pepmorph,0.755346,0.049312,2.071813,0.007323,3,3,0.703003,0.762104,0.800930,2.063410,2.075192,2.076836
112,IVLFIF,sphere_pepmorph,0.754414,0.067726,2.455844,0.048843,3,3,0.766112,0.815530,0.681601,2.407728,2.454420,2.505383
113,LIIVF,sphere_pepmorph,0.781477,0.069139,1.983241,0.052856,3,3,0.730597,0.753638,0.860195,1.949825,1.955719,2.044179
114,LVIIF,sphere_pepmorph,0.697895,0.127500,1.982113,0.042879,3,3,0.801390,0.555468,0.736827,2.006760,1.932601,2.006979
115,VFFIF,sphere_pepmorph,0.906594,0.014674,2.902559,0.029800,3,3,0.911413,0.890116,0.918253,2.870044,2.928571,2.909062
116,VIFIL,sphere_pepmorph,0.668102,0.097296,1.960551,0.033630,3,3,0.705582,0.557639,0.741084,1.924503,1.991081,1.966068

In [33]:
# show peptides with AP >- 1.8 by run with majority vote
merged_sphere_pepmorph_by_run = merged_by_run[merged_by_run['class'] == 'sphere_pepmorph']
print(f'Sphere_pepmorph Peptides by run with aggregation_propensity >= 1.8 in majority of runs: {len(merged_sphere_pepmorph_by_run[merged_sphere_pepmorph_by_run["aggregation_propensity"] >= 1.8])}')
merged_sphere_pepmorph_by_run_majority = merged_sphere_pepmorph_by_run.groupby('peptide').agg(
    majority_ap=('aggregation_propensity', lambda x: (x >= 1.8).sum() > (len(x) / 2))
).reset_index()
merged_sphere_pepmorph_by_run_majority = merged_sphere_pepmorph_by_run_majority[merged_sphere_pepmorph_by_run_majority['majority_ap']]
print(f'Length of merged_sphere_pepmorph_by_run_majority:', len(merged_sphere_pepmorph_by_run_majority))
merged_sphere_pepmorph_by_run_majority

Sphere_pepmorph Peptides by run with aggregation_propensity >= 1.8 in majority of runs: 45
Length of merged_sphere_pepmorph_by_run_majority: 15

   peptide  majority_ap
0    FFIFI         True
1    FFLFI         True
2    FIFIF         True
3    FIFVF         True
4    FIVFF         True
5   FIVVIF         True
6   FLIFFI         True
7    FVIFF         True
8    FVIVI         True
9    IVFVI         True
10  IVLFIF         True
11   LIIVF         True
12   LVIIF         True
13   VFFIF         True
14   VIFIL         True

In [34]:
# show merged with class='fiber_pepmorph'
merged_fiber_pepmorph = merged[merged['class'] == 'fiber_pepmorph']
print('Length of merged_fiber_pepmorph:', len(merged_fiber_pepmorph))

Length of merged_fiber_pepmorph: 15

In [35]:
# show peptides with AP >= 1.8
print(f'Fiber_pepmorph Peptides with aggregation_propensity_mean >= 1.8: {len(merged_fiber_pepmorph[merged_fiber_pepmorph["aggregation_propensity_mean"] >= 1.8])}')
merged_fiber_pepmorph[merged_fiber_pepmorph['aggregation_propensity_mean'] >= 1.8]

Fiber_pepmorph Peptides with aggregation_propensity_mean >= 1.8: 15

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
87,CVSAPGIFHC,fiber_pepmorph,0.376627,0.070951,1.959019,0.058305,3,3,0.295179,0.409692,0.425011,2.022145,1.947726,1.907187
88,FTFIPGWVDL,fiber_pepmorph,0.398661,0.096232,2.439498,0.078677,3,3,0.307051,0.390002,0.498930,2.478425,2.491124,2.348946
89,HYVSGRFLIY,fiber_pepmorph,0.495999,0.025635,2.212450,0.053054,3,3,0.520591,0.497972,0.469435,2.176169,2.187840,2.273340
90,ILSCPGWPFY,fiber_pepmorph,0.257501,0.339623,2.810913,0.009507,3,3,0.240490,0.845007,0.274513,2.817635,2.525681,2.804190
91,ILSFPDKVTY,fiber_pepmorph,0.398988,0.089944,2.194466,0.054625,3,3,0.458935,0.442462,0.295566,2.134727,2.241865,2.206807
92,LDIYNHPFF,fiber_pepmorph,0.264959,0.024398,2.603789,0.017323,3,3,0.278190,0.279883,0.236803,2.585237,2.619542,2.606587
93,LFLTADSYCF,fiber_pepmorph,0.290627,0.036471,2.533485,0.033179,3,3,0.268675,0.270478,0.332727,2.504544,2.526214,2.569697
94,LICWTGHCHH,fiber_pepmorph,0.509004,0.078107,2.225725,0.074194,3,3,0.577594,0.423991,0.525428,2.183927,2.311389,2.181859
95,PAPFPWSIWI,fiber_pepmorph,0.455344,0.127478,3.063479,0.091485,3,3,0.533439,0.308239,0.524355,3.037179,3.165233,2.988025
96,PFAIPYCSTP,fiber_pepmorph,0.603115,0.303063,2.581682,0.057404,3,3,0.291260,0.896545,0.621539,2.606192,2.622762,2.516091
97,PVFCADQWFC,fiber_pepmorph,0.323134,0.029621,2.846021,0.107717,3,3,0.356060,0.298652,0.314689,2.721827,2.902227,2.914010
98,PVWRADSWHC,fiber_pepmorph,0.529067,0.047608,2.443341,0.049071,3,3,0.507244,0.496283,0.583675,2.466513,2.386975,2.476534
99,QIRTYDFLVF,fiber_pepmorph,0.687460,0.145185,2.160115,0.005033,3,3,0.817163,0.530622,0.714594,2.154567,2.161391,2.164387
100,RAVYGDFVFL,fiber_pepmorph,0.376509,0.030850,2.173862,0.024415,3,3,0.362986,0.411811,0.354731,2.176637,2.196771,2.148178
101,VFLVPVDFKY,fiber_pepmorph,0.580725,0.255395,2.789320,0.043639,3,3,0.351668,0.534394,0.856114,2.740966,2.801216,2.825777

In [36]:
# show peptides with AP >- 1.8 by run with majority vote
merged_fiber_pepmorph_by_run = merged_by_run[merged_by_run['class'] == 'fiber_pepmorph']
print(f'Fiber_pepmorph Peptides by run with aggregation_propensity >= 1.8 in majority of runs: {len(merged_fiber_pepmorph_by_run[merged_fiber_pepmorph_by_run["aggregation_propensity"] >= 1.8])}')
merged_fiber_pepmorph_by_run_majority = merged_fiber_pepmorph_by_run.groupby('peptide').agg(
    majority_ap=('aggregation_propensity', lambda x: (x >= 1.8).sum() > (len(x) / 2))
).reset_index()
merged_fiber_pepmorph_by_run_majority = merged_fiber_pepmorph_by_run_majority[merged_fiber_pepmorph_by_run_majority['majority_ap']]
print(f'Length of merged_fiber_pepmorph_by_run_majority:', len(merged_fiber_pepmorph_by_run_majority))
merged_fiber_pepmorph_by_run_majority

Fiber_pepmorph Peptides by run with aggregation_propensity >= 1.8 in majority of runs: 45
Length of merged_fiber_pepmorph_by_run_majority: 15

       peptide  majority_ap
0   CVSAPGIFHC         True
1   FTFIPGWVDL         True
2   HYVSGRFLIY         True
3   ILSCPGWPFY         True
4   ILSFPDKVTY         True
5    LDIYNHPFF         True
6   LFLTADSYCF         True
7   LICWTGHCHH         True
8   PAPFPWSIWI         True
9   PFAIPYCSTP         True
10  PVFCADQWFC         True
11  PVWRADSWHC         True
12  QIRTYDFLVF         True
13  RAVYGDFVFL         True
14  VFLVPVDFKY         True

In [37]:
# show merged with class=NaN
merged_nan = merged[merged['class'].isna()]
print('Length of merged_nan:', len(merged_nan))
merged_nan

Length of merged_nan: 0

Empty DataFrame
Columns: [peptide, class, RMOI_mean, RMOI_std, aggregation_propensity_mean, aggregation_propensity_std, n_runs_RMOI, n_runs_AP, RMOI_run_1, RMOI_run_2, RMOI_run_3, aggregation_propensity_run_1, aggregation_propensity_run_2, aggregation_propensity_run_3]
Index: []

In [38]:
# adapt merged to have a 'has_aggregated' column
# also a 'matches_morphology' for fiber and sphere targets, if RMOI_mean is >=0.75 for spheres and <=0.35 for fibers
def has_aggregated(row):
    return row['aggregation_propensity_mean'] >= 1.8

def matches_morphology(row):
    if not has_aggregated(row):
        return False
    if row['class'] == 'fiber_no_desc' or row['class'] == 'fiber_no_ap' or row['class'] == 'fiber_pepmorph':
        return row['RMOI_mean'] <= 0.35
    elif row['class'] == 'sphere_no_desc' or row['class'] == 'sphere_no_ap' or row['class'] == 'sphere_pepmorph':
        return row['RMOI_mean'] >= 0.75
    else:
        return False
    
merged['has_aggregated'] = merged.apply(has_aggregated, axis=1)
merged['matches_morphology'] = merged.apply(matches_morphology, axis=1)
merged

,peptide,class,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3,has_aggregated,matches_morphology
0,EFAHHYNQIL,fiber_no_ap,0.563333,0.084213,1.438246,0.031033,3,3,0.660130,0.506904,0.522966,1.413070,1.428751,1.472918,False,False
1,VSVQPMECH,fiber_no_ap,0.442553,0.046878,1.377653,0.006778,3,3,0.407730,0.424076,0.495854,1.385169,1.372005,1.375784,False,False
2,LYRPAPLEL,fiber_no_ap,0.343279,0.049025,1.716276,0.017749,3,3,0.328363,0.303444,0.398030,1.725839,1.727192,1.695796,False,False
3,LQICQWAA,fiber_no_ap,0.481083,0.083499,1.831733,0.053068,3,3,0.472290,0.402329,0.568631,1.835404,1.776925,1.882870,True,False
4,DAPFIMAY,fiber_no_ap,0.612673,0.078738,1.655658,0.027332,3,3,0.632853,0.525810,0.679358,1.643816,1.636244,1.686914,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,IVLFIF,sphere_pepmorph,0.754414,0.067726,2.455844,0.048843,3,3,0.766112,0.815530,0.681601,2.407728,2.454420,2.505383,True,True
113,LIIVF,sphere_pepmorph,0.781477,0.069139,1.983241,0.052856,3,3,0.730597,0.753638,0.860195,1.949825,1.955719,2.044179,True,True
114,LVIIF,sphere_pepmorph,0.697895,0.127500,1.982113,0.042879,3,3,0.801390,0.555468,0.736827,2.006760,1.932601,2.006979,True,False
115,VFFIF,sphere_pepmorph,0.906594,0.014674,2.902559,0.029800,3,3,0.911413,0.890116,0.918253,2.870044,2.928571,2.909062,True,True
116,VIFIL,sphere_pepmorph,0.668102,0.097296,1.960551,0.033630,3,3,0.705582,0.557639,0.741084,1.924503,1.991081,1.966068,True,False

In [39]:
# apply has_aggregated and matches_morphology by run
def has_aggregated_by_run(row):
    return row['aggregation_propensity'] >= 1.8

def matches_morphology_by_run(row):
    if not has_aggregated_by_run(row):
        return False
    if row['class'] == 'fiber_no_desc' or row['class'] == 'fiber_no_ap' or row['class'] == 'fiber_pepmorph':
        return row['RMOI'] <= 0.35
    elif row['class'] == 'sphere_no_desc' or row['class'] == 'sphere_no_ap' or row['class'] == 'sphere_pepmorph':
        return row['RMOI'] >= 0.75
    else:
        return False

def matches_morphology_visually_by_run(row):
    return row['is_target'] == "yes"

merged_by_run['has_aggregated'] = merged_by_run.apply(has_aggregated_by_run, axis=1)
merged_by_run['matches_morphology'] = merged_by_run.apply(matches_morphology_by_run, axis=1)
merged_by_run['matches_morphology_visually'] = merged_by_run.apply(matches_morphology_visually_by_run, axis=1)
merged_by_run

,peptide,class,run,RMOI,aggregation_propensity,visual_morphology,is_target,has_aggregated,matches_morphology,matches_morphology_visually
0,EFAHHYNQIL,fiber_no_ap,run_1,0.660130,1.413070,NaN,NaN,False,False,False
1,EFAHHYNQIL,fiber_no_ap,run_2,0.506904,1.428751,NaN,NaN,False,False,False
2,EFAHHYNQIL,fiber_no_ap,run_3,0.522966,1.472918,NaN,NaN,False,False,False
3,VSVQPMECH,fiber_no_ap,run_1,0.407730,1.385169,NaN,NaN,False,False,False
4,VSVQPMECH,fiber_no_ap,run_2,0.424076,1.372005,NaN,NaN,False,False,False
...,...,...,...,...,...,...,...,...,...,...
346,RAVYGDFVFL,fiber_pepmorph,run_2,0.411811,2.196771,sheet string-like,no,True,False,False
347,RAVYGDFVFL,fiber_pepmorph,run_3,0.354731,2.148178,fiber intertwined,yes,True,False,True
348,VFLVPVDFKY,fiber_pepmorph,run_1,0.351668,2.740966,fiber,yes,True,False,True
349,VFLVPVDFKY,fiber_pepmorph,run_2,0.534394,2.801216,vesicle,no,True,False,False
350,VFLVPVDFKY,fiber_pepmorph,run_3,0.856114,2.825777,vesicle,no,True,False,False

In [40]:
# produce summary statistics by class
summary = merged.groupby('class').agg(
    total_peptides=('peptide', 'count'),
    aggregated_peptides=('has_aggregated', 'sum'),
    morphology_matches=('matches_morphology', 'sum')
).reset_index()

summary

             class  total_peptides  aggregated_peptides  morphology_matches
0      fiber_no_ap              15                    4                   0
1    fiber_no_desc              15                   13                   1
2   fiber_pepmorph              15                   15                   4
3           random              15                    2                   0
4     sphere_no_ap              15                    1                   0
5   sphere_no_desc              15                   13                   3
6  sphere_pepmorph              15                   15                  11
7     unsupervised              12                    7                   0

In [41]:
# do summary statistics by class for by run with majority vote
summary_by_run = merged_by_run.groupby(['peptide', 'class']).agg(
    majority_aggregated=('has_aggregated', lambda x: x.sum() > (len(x) / 2)),
    majority_morphology_matches=('matches_morphology', lambda x: x.sum() > (len(x) / 2))
).reset_index()

summary_by_run = summary_by_run.groupby('class').agg(
    total_peptides=('peptide', 'count'),
    aggregated_peptides=('majority_aggregated', 'sum'),
    morphology_matches=('majority_morphology_matches', 'sum')
).reset_index()

summary_by_run

             class  total_peptides  aggregated_peptides  morphology_matches
0      fiber_no_ap              15                    4                   0
1    fiber_no_desc              15                   13                   3
2   fiber_pepmorph              15                   15                   4
3           random              15                    3                   0
4     sphere_no_ap              15                    1                   0
5   sphere_no_desc              15                   13                   6
6  sphere_pepmorph              15                   15                  11
7     unsupervised              12                    7                   0

In [42]:
# take only random and unsupervised runs from merged_by_run
merged_random_unsupervised_by_run = merged_by_run[merged_by_run['class'].isin(['random', 'unsupervised'])]
merged_random_unsupervised_by_run

,peptide,class,run,RMOI,aggregation_propensity,visual_morphology,is_target,has_aggregated,matches_morphology,matches_morphology_visually
180,MEIDC,random,run_1,0.761112,1.044081,NaN,NaN,False,False,False
181,MEIDC,random,run_2,0.730371,1.048177,NaN,NaN,False,False,False
182,MEIDC,random,run_3,0.798412,1.046261,NaN,NaN,False,False,False
183,NGCAN,random,run_1,0.474494,1.051729,NaN,NaN,False,False,False
184,NGCAN,random,run_2,0.454973,1.053886,NaN,NaN,False,False,False
...,...,...,...,...,...,...,...,...,...,...
256,YPDYSM,unsupervised,run_2,0.211401,2.009141,NaN,NaN,True,False,False
257,YPDYSM,unsupervised,run_3,0.309647,1.969406,NaN,NaN,True,False,False
258,YYCDVERMIC,unsupervised,run_1,0.307397,1.917980,NaN,NaN,True,False,False
259,YYCDVERMIC,unsupervised,run_2,0.507472,1.832180,NaN,NaN,True,False,False
260,YYCDVERMIC,unsupervised,run_3,0.308073,1.885899,NaN,NaN,True,False,False

In [43]:
# get number of spheres and number of fibers based on RMOI from runs
# based on has_aggregated=True and majority vote
def is_fiber(row):
    return row['has_aggregated'] and row['RMOI'] <= 0.35
def is_sphere(row):
    return row['has_aggregated'] and row['RMOI'] >= 0.75

merged_random_unsupervised_by_run['is_fiber'] = merged_random_unsupervised_by_run.apply(is_fiber, axis=1)
merged_random_unsupervised_by_run['is_sphere'] = merged_random_unsupervised_by_run.apply(is_sphere, axis=1)

merged_random_unsupervised_by_run

/tmp/ipykernel_234553/269569663.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_random_unsupervised_by_run['is_fiber'] = merged_random_unsupervised_by_run.apply(is_fiber, axis=1)
/tmp/ipykernel_234553/269569663.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_random_unsupervised_by_run['is_sphere'] = merged_random_unsupervised_by_run.apply(is_sphere, axis=1)

,peptide,class,run,RMOI,aggregation_propensity,visual_morphology,is_target,has_aggregated,matches_morphology,matches_morphology_visually,is_fiber,is_sphere
180,MEIDC,random,run_1,0.761112,1.044081,NaN,NaN,False,False,False,False,False
181,MEIDC,random,run_2,0.730371,1.048177,NaN,NaN,False,False,False,False,False
182,MEIDC,random,run_3,0.798412,1.046261,NaN,NaN,False,False,False,False,False
183,NGCAN,random,run_1,0.474494,1.051729,NaN,NaN,False,False,False,False,False
184,NGCAN,random,run_2,0.454973,1.053886,NaN,NaN,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
256,YPDYSM,unsupervised,run_2,0.211401,2.009141,NaN,NaN,True,False,False,True,False
257,YPDYSM,unsupervised,run_3,0.309647,1.969406,NaN,NaN,True,False,False,True,False
258,YYCDVERMIC,unsupervised,run_1,0.307397,1.917980,NaN,NaN,True,False,False,True,False
259,YYCDVERMIC,unsupervised,run_2,0.507472,1.832180,NaN,NaN,True,False,False,False,False
260,YYCDVERMIC,unsupervised,run_3,0.308073,1.885899,NaN,NaN,True,False,False,True,False

In [44]:
# get summary statistics
summary_random_unsupervised_by_run = merged_random_unsupervised_by_run.groupby(['peptide', 'class']).agg(
    majority_fiber=('is_fiber', lambda x: x.sum() > (len(x) / 2)),
    majority_sphere=('is_sphere', lambda x: x.sum() > (len(x) / 2))
).reset_index()
summary_random_unsupervised_by_run = summary_random_unsupervised_by_run.groupby('class').agg(
    total_peptides=('peptide', 'count'),
    fiber_peptides=('majority_fiber', 'sum'),
    sphere_peptides=('majority_sphere', 'sum')
).reset_index()
summary_random_unsupervised_by_run

          class  total_peptides  fiber_peptides  sphere_peptides
0        random              15               0                0
1  unsupervised              12               4                1

In [45]:
merged[['peptide', 'class', 'aggregation_propensity_mean', 'RMOI_mean', 'has_aggregated', 'matches_morphology']].to_csv('analysis_new.csv', index=False)

In [46]:
# if has_aggregated is True, set matches_morphology_visually to TBD
# else set matches_morphology_visually to False
def matches_morphology_visually(row):
    if row['is_target']:
        return row['is_target']
    if row['has_aggregated']:
        return 'TBD'
    else:
        return False

merged_by_run['is_target'] = merged_by_run.apply(matches_morphology_visually, axis=1)
merged_by_run[['peptide', 'class', 'run', 'aggregation_propensity', 'RMOI', 'has_aggregated', 'matches_morphology', 'is_target', 'visual_morphology']].to_csv('analysis_by_run.csv', index=False)

In [47]:
merged_by_run

,peptide,class,run,RMOI,aggregation_propensity,visual_morphology,is_target,has_aggregated,matches_morphology,matches_morphology_visually
0,EFAHHYNQIL,fiber_no_ap,run_1,0.660130,1.413070,NaN,NaN,False,False,False
1,EFAHHYNQIL,fiber_no_ap,run_2,0.506904,1.428751,NaN,NaN,False,False,False
2,EFAHHYNQIL,fiber_no_ap,run_3,0.522966,1.472918,NaN,NaN,False,False,False
3,VSVQPMECH,fiber_no_ap,run_1,0.407730,1.385169,NaN,NaN,False,False,False
4,VSVQPMECH,fiber_no_ap,run_2,0.424076,1.372005,NaN,NaN,False,False,False
...,...,...,...,...,...,...,...,...,...,...
346,RAVYGDFVFL,fiber_pepmorph,run_2,0.411811,2.196771,sheet string-like,no,True,False,False
347,RAVYGDFVFL,fiber_pepmorph,run_3,0.354731,2.148178,fiber intertwined,yes,True,False,True
348,VFLVPVDFKY,fiber_pepmorph,run_1,0.351668,2.740966,fiber,yes,True,False,True
349,VFLVPVDFKY,fiber_pepmorph,run_2,0.534394,2.801216,vesicle,no,True,False,False
350,VFLVPVDFKY,fiber_pepmorph,run_3,0.856114,2.825777,vesicle,no,True,False,False

In [48]:
# create a folder named per_class
# inside per_class, create a folder for each class
# there are 3 folders: run_1, run_2, run_3
# copy the corresponding peptide folder (named by peptide) into the correct class folder
# e.g., per_class/run_1/random/peptide_001, per_class/run_1/unsupervised/peptide_002, etc.
"""
import os
import shutil
classes = merged['class'].unique()

for run in ['run_1', 'run_2', 'run_3']:
    for cls in classes:
        dir_path = os.path.join('per_class', run, cls)
        os.makedirs(dir_path, exist_ok=True)

        peptides_in_class = merged_by_run[(merged_by_run['class'] == cls) & (merged_by_run['run'] == run)]['peptide'].unique()
        for peptide in peptides_in_class:
            src = os.path.join('..', run, peptide)
            dst = os.path.join(dir_path, peptide)
            if os.path.exists(src):
                shutil.copytree(src, dst)"""

"\nimport os\nimport shutil\nclasses = merged['class'].unique()\n\nfor run in ['run_1', 'run_2', 'run_3']:\n    for cls in classes:\n        dir_path = os.path.join('per_class', run, cls)\n        os.makedirs(dir_path, exist_ok=True)\n\n        peptides_in_class = merged_by_run[(merged_by_run['class'] == cls) & (merged_by_run['run'] == run)]['peptide'].unique()\n        for peptide in peptides_in_class:\n            src = os.path.join('..', run, peptide)\n            dst = os.path.join(dir_path, peptide)\n            if os.path.exists(src):\n                shutil.copytree(src, dst)"

In [49]:
COHORT_LABEL = {
    # Untargeted
    "random": "Random",
    "unsupervised": "Unsupervised",

    # Spherical-targeted
    "sphere_no_ap": "Failed AP screen",
    "sphere_no_desc": "Failed descriptor screen",
    "sphere_pepmorph": "PepMorph candidates",

    # Fibril-targeted
    "fiber_no_ap": "Failed AP screen",
    "fiber_no_desc": "Failed descriptor screen",
    "fiber_pepmorph": "PepMorph candidates",
}


SECTION_LABEL = {
    "random": "Untargeted",
    "unsupervised": "Untargeted",

    "sphere_no_ap": "Spherical-targeted",
    "sphere_no_desc": "Spherical-targeted",
    "sphere_pepmorph": "Spherical-targeted",

    "fiber_no_ap": "Fibril-targeted",
    "fiber_no_desc": "Fibril-targeted",
    "fiber_pepmorph": "Fibril-targeted",
}

## Post Visual Assessment

In [100]:
import numpy as np
import pandas as pd
from collections import Counter
from scipy.stats import fisher_exact
from statsmodels.stats.contingency_tables import Table2x2

In [101]:
def wilson_ci(k: int, n: int, alpha: float = 0.05):
    """Wilson score CI for a binomial proportion."""
    if n == 0:
        return (np.nan, np.nan)
    z = 1.959963984540054  # ~N(0,1) 97.5% quantile for 95% CI
    p = k / n
    denom = 1 + z*z/n
    center = (p + z*z/(2*n)) / denom
    half = (z * np.sqrt((p*(1-p)/n) + (z*z/(4*n*n)))) / denom
    return (float(center - half), float(center + half))

def fisher_or_ci(a, b, c, d, alpha: float = 0.05):
    """
    2x2 with:
      PepMorph: success=a, fail=b
      Control : success=c, fail=d
    Returns odds_ratio, (lo, hi), p_value.
    """
    table_int = np.array([[a, b], [c, d]], dtype=int)
    or_scipy, p = fisher_exact(table_int, alternative="two-sided")

    # CI for OR
    if (table_int == 0).any():
        # Haldane-Anscombe correction for stability
        table = table_int.astype(float) + 0.5
        ct = Table2x2(table)
        or_hat = float(ct.oddsratio)
        lo, hi = ct.oddsratio_confint(alpha=alpha, method="wald")
    else:
        ct = Table2x2(table_int)
        or_hat = float(ct.oddsratio)
        try:
            lo, hi = ct.oddsratio_confint(alpha=alpha, method="exact")
        except Exception:
            lo, hi = ct.oddsratio_confint(alpha=alpha, method="wald")
    return or_hat, (float(lo), float(hi)), float(p)

In [102]:
import pandas as pd

def normalize_visual_label(row):
    """
    Per-run label used ONLY for voting:
      'S' = sphere-like
      'F' = fibril/tube-like
      'O' = other / not classified as S or F / did not match target
    """
    cls = str(row.get("class", "")).strip().lower()
    it  = row.get("is_target", None)
    it  = "" if (it is None or (isinstance(it, float) and pd.isna(it))) else str(it).strip().lower()

    if it in {"t", "tube", "tubes", "tubular", "fibril", "fibrils"}:
        it = "fiber"
    if it in {"s", "sphere", "spheres", "spherical"}:
        it = "sphere"

    if cls in {"random", "unsupervised"}:
        if it == "sphere":
            return "S"
        if it == "fiber":
            return "F"
        return "O"

    target = None
    if "sphere" in cls:
        target = "S"
    elif ("fiber" in cls) or ("fibril" in cls):
        target = "F"

    if it == "yes":
        return target if target is not None else "O"
    if it == "no" or it == "":
        return "O"

    if it == "sphere":
        return "S"
    if it == "fiber":
        return "F"

    return "O"

def majority_vote_strict(vals):
    """
    Returns:
      'S' or 'F' only if it has a strict majority among votes (including 'O').
      Otherwise returns 'O'.

    With 3 runs: requires 2 votes for S or F.
    """
    vals = [v for v in vals if v is not None]
    if not vals:
        return None

    c = Counter(vals)
    n = len(vals)
    need = (n // 2) + 1

    if c["S"] >= need:
        return "S"
    if c["F"] >= need:
        return "F"
    return "O"


def collapse_runs_to_peptides(df_runs: pd.DataFrame,
                              ap_thresh=1.8,
                              rmoi_sphere_thresh=0.75,
                              rmoi_fiber_thresh=0.35):
    df = df_runs.copy()

    required = ["peptide", "class", "run", "aggregation_propensity", "RMOI", "is_target"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"CSV missing required columns: {missing}")

    df["aggregation_propensity"] = pd.to_numeric(df["aggregation_propensity"], errors="coerce")
    df["RMOI"] = pd.to_numeric(df["RMOI"], errors="coerce")

    df["ap_pass"] = df["aggregation_propensity"] >= ap_thresh
    df["rmoi_pass_sphere"] = df["RMOI"] >= rmoi_sphere_thresh
    df["rmoi_pass_fiber"]  = df["RMOI"] <= rmoi_fiber_thresh

    df["vis_norm"] = df.apply(normalize_visual_label, axis=1)

    def strict_majority_bool(bools):
        bools = [bool(x) for x in bools if x is not None and not (isinstance(x, float) and pd.isna(x))]
        if not bools:
            return False
        need = (len(bools) // 2) + 1
        return sum(bools) >= need

    g = df.groupby(["class", "peptide"], as_index=False).agg(
        ap_mean=("aggregation_propensity", "mean"),
        rmoi_mean=("RMOI", "mean"),
        ap_majority=("ap_pass", strict_majority_bool),
        rmoi_majority_sphere=("rmoi_pass_sphere", strict_majority_bool),
        rmoi_majority_fiber=("rmoi_pass_fiber", strict_majority_bool),
        vis_majority=("vis_norm", lambda s: majority_vote_strict(list(s))),
        vis_any_S=("vis_norm", lambda s: any(v == "S" for v in s if v is not None)),
        vis_any_F=("vis_norm", lambda s: any(v == "F" for v in s if v is not None)),
    )
    return g

In [103]:
def compute_descriptive_values(
    df_pep: pd.DataFrame,
    *,
    ap_thresh: float = 1.8,
    rmoi_sphere_thresh: float = 0.75,
    rmoi_fiber_thresh: float = 0.35,
    class_meta: dict,
    untargeted_mode: str = "majority",
):
    """
    Returns a DataFrame with all values needed for the paper Table 6.

    class_meta: dict mapping class -> dict with keys:
      - section: "Untargeted" / "Spherical-targeted" / "Fibril-targeted"
      - cohort: row label, e.g. "Failed AP screen"
      - target: None (untargeted) or "sphere" or "fiber"
    """
    df = df_pep.copy()

    df["has_agg"] = df["ap_majority"]
    df["rmoi_is_sphere"] = df["rmoi_majority_sphere"]
    df["rmoi_is_fiber"]  = df["rmoi_majority_fiber"]

    rows = []
    for cls, meta in class_meta.items():
        sub = df[df["class"] == cls].copy()
        n = int(sub["peptide"].nunique())
        agg = sub[sub["has_agg"]].copy()
        n_agg = int(agg["peptide"].nunique())

        # Aggregation rate (unconditional)
        agg_rate = (n_agg / n) if n else np.nan

        target = meta.get("target", None)  # None / "sphere" / "fiber"

        out = dict(
            class_key=cls,
            section=meta.get("section", ""),
            cohort=meta.get("cohort", cls),
            n_total=n,
            n_agg=n_agg,
            agg_rate=agg_rate,
        )

        if target is None:
            # Untargeted: report S and F fractions among aggregators
            if n_agg == 0:
                out.update(
                    rmoi_S_k=0, rmoi_F_k=0, vis_S_k=0, vis_F_k=0,
                    rmoi_S_rate=np.nan, rmoi_F_rate=np.nan,
                    vis_S_rate=np.nan, vis_F_rate=np.nan,
                )
                rows.append(out)
                continue

            if untargeted_mode == "any_run":
                rmoi_S_k = int(agg["rmoi_any_S"].sum())
                rmoi_F_k = int(agg["rmoi_any_F"].sum())
                vis_S_k  = int(agg["vis_any_S"].sum())
                vis_F_k  = int(agg["vis_any_F"].sum())
            elif untargeted_mode == "majority":
                rmoi_S_k = int(agg["rmoi_is_sphere"].sum())
                rmoi_F_k = int(agg["rmoi_is_fiber"].sum())
                vis_S_k  = int((agg["vis_majority"] == "S").sum())
                vis_F_k  = int((agg["vis_majority"] == "F").sum())
            else:
                raise ValueError("untargeted_mode must be 'majority' or 'any_run'")

            out.update(
                rmoi_S_k=rmoi_S_k,
                rmoi_F_k=rmoi_F_k,
                vis_S_k=vis_S_k,
                vis_F_k=vis_F_k,
                rmoi_S_rate=rmoi_S_k / n_agg,
                rmoi_F_rate=rmoi_F_k / n_agg,
                vis_S_rate=vis_S_k / n_agg,
                vis_F_rate=vis_F_k / n_agg,
            )
            rows.append(out)
            continue

        # Targeted cohorts: success conditional on aggregation
        if n_agg == 0:
            out.update(
                rmoi_succ_k=0, rmoi_succ_rate=np.nan,
                vis_succ_k=0,  vis_succ_rate=np.nan,
            )
            rows.append(out)
            continue

        if target == "sphere":
            rmoi_succ_k = int(agg["rmoi_is_sphere"].sum())
            vis_succ_k  = int((agg["vis_majority"] == "S").sum())
        elif target == "fiber":
            rmoi_succ_k = int(agg["rmoi_is_fiber"].sum())
            vis_succ_k  = int((agg["vis_majority"] == "F").sum())
        else:
            raise ValueError(f"Unknown target: {target}")

        out.update(
            rmoi_succ_k=rmoi_succ_k,
            rmoi_succ_rate=rmoi_succ_k / n_agg,
            vis_succ_k=vis_succ_k,
            vis_succ_rate=vis_succ_k / n_agg,
        )
        rows.append(out)

    out_df = pd.DataFrame(rows)

    # Convenience formatted fields matching the table style
    def fmt_pct(k, n):
        return "--" if n == 0 else f"{100.0*k/n:.1f}% ({k}/{n})"

    out_df["agg_rate_str"] = out_df.apply(lambda r: fmt_pct(int(r["n_agg"]), int(r["n_total"])), axis=1)

    # For untargeted vs targeted, add corresponding strings
    def rmoi_str(r):
        if r["section"] == "Untargeted":
            if r["n_agg"] == 0:
                return "S: -- ; F: --"
            return f"S: {fmt_pct(int(r['rmoi_S_k']), int(r['n_agg']))} ; F: {fmt_pct(int(r['rmoi_F_k']), int(r['n_agg']))}"
        else:
            if r["n_agg"] == 0:
                return "--"
            return fmt_pct(int(r["rmoi_succ_k"]), int(r["n_agg"]))

    def vis_str(r):
        if r["section"] == "Untargeted":
            if r["n_agg"] == 0:
                return "S: -- ; F: --"
            return f"S: {fmt_pct(int(r['vis_S_k']), int(r['n_agg']))} ; F: {fmt_pct(int(r['vis_F_k']), int(r['n_agg']))}"
        else:
            if r["n_agg"] == 0:
                return "--"
            return fmt_pct(int(r["vis_succ_k"]), int(r["n_agg"]))

    out_df["rmoi_outcome_str"] = out_df.apply(rmoi_str, axis=1)
    out_df["visual_outcome_str"] = out_df.apply(vis_str, axis=1)

    return out_df


def compute_rates_values(
    df_pep: pd.DataFrame,
    *,
    ap_thresh: float = 1.8,
    sphere_pepmorph_class: str,
    sphere_descfail_class: str,
    fiber_pepmorph_class: str,
    fiber_descfail_class: str,
):
    """
    Computes visual outcomes (conditional on aggregation) and Fisher OR/p for:
      - Spheres: PepMorph vs Desc-fail
      - Fibrils: PepMorph vs Desc-fail
      - All pooled: combine both targets
    Returns (rates_df, stats_df).
    """
    df = df_pep.copy()
    df["has_agg"] = df["ap_majority"]

    def block(target_name, pep_cls, ctrl_cls, success_label):
        pep = df[(df["class"] == pep_cls) & (df["has_agg"])].copy()
        ctrl = df[(df["class"] == ctrl_cls) & (df["has_agg"])].copy()

        n1 = int(pep["peptide"].nunique())
        n0 = int(ctrl["peptide"].nunique())

        s1 = int((pep["vis_majority"] == success_label).sum())
        s0 = int((ctrl["vis_majority"] == success_label).sum())

        lo1, hi1 = wilson_ci(s1, n1)
        lo0, hi0 = wilson_ci(s0, n0)

        or_hat, (or_lo, or_hi), p = fisher_or_ci(s1, n1 - s1, s0, n0 - s0)

        rates = [
            dict(target=target_name, cohort="PepMorph", success_k=s1, n=n1, rate=(s1/n1 if n1 else np.nan), ci_lo=lo1, ci_hi=hi1),
            dict(target=target_name, cohort="Desc.-fail", success_k=s0, n=n0, rate=(s0/n0 if n0 else np.nan), ci_lo=lo0, ci_hi=hi0),
        ]
        stats = dict(target=target_name, fisher_or=or_hat, or_ci_lo=or_lo, or_ci_hi=or_hi, p_value=p,
                     pep_success=s1, pep_n=n1, ctrl_success=s0, ctrl_n=n0)
        return rates, stats

    rates_all = []
    stats_all = []

    r, s = block("Spheres", sphere_pepmorph_class, sphere_descfail_class, success_label="S")
    rates_all += r; stats_all.append(s)

    r, s = block("Fibrils", fiber_pepmorph_class, fiber_descfail_class, success_label="F")
    rates_all += r; stats_all.append(s)

    # pooled
    # pool the underlying 2x2 counts directly
    sph = stats_all[0]
    fib = stats_all[1]
    a = sph["pep_success"] + fib["pep_success"]
    b = (sph["pep_n"] - sph["pep_success"]) + (fib["pep_n"] - fib["pep_success"])
    c = sph["ctrl_success"] + fib["ctrl_success"]
    d = (sph["ctrl_n"] - sph["ctrl_success"]) + (fib["ctrl_n"] - fib["ctrl_success"])

    # pooled rates/CI
    pep_n = sph["pep_n"] + fib["pep_n"]
    pep_s = sph["pep_success"] + fib["pep_success"]
    ctrl_n = sph["ctrl_n"] + fib["ctrl_n"]
    ctrl_s = sph["ctrl_success"] + fib["ctrl_success"]

    pep_lo, pep_hi = wilson_ci(pep_s, pep_n)
    ctrl_lo, ctrl_hi = wilson_ci(ctrl_s, ctrl_n)

    pooled_or, (pooled_lo, pooled_hi), pooled_p = fisher_or_ci(a, b, c, d)

    rates_all += [
        dict(target="All pooled", cohort="PepMorph", success_k=pep_s, n=pep_n, rate=(pep_s/pep_n if pep_n else np.nan), ci_lo=pep_lo, ci_hi=pep_hi),
        dict(target="All pooled", cohort="Desc.-fail", success_k=ctrl_s, n=ctrl_n, rate=(ctrl_s/ctrl_n if ctrl_n else np.nan), ci_lo=ctrl_lo, ci_hi=ctrl_hi),
    ]
    stats_all.append(dict(target="All pooled", fisher_or=pooled_or, or_ci_lo=pooled_lo, or_ci_hi=pooled_hi, p_value=pooled_p,
                          pep_success=pep_s, pep_n=pep_n, ctrl_success=ctrl_s, ctrl_n=ctrl_n))

    rates_df = pd.DataFrame(rates_all)
    stats_df = pd.DataFrame(stats_all)

    return rates_df, stats_df

In [104]:
CSV_PATH = "analysis_by_run.csv"
df_runs = pd.read_csv(CSV_PATH)
df_pep = collapse_runs_to_peptides(df_runs)

class_meta = {
    "random":          {"section": "Untargeted",          "cohort": "Random",                 "target": None},
    "unsupervised":    {"section": "Untargeted",          "cohort": "Unsupervised",           "target": None},

    "sphere_no_ap":    {"section": "Spherical-targeted",  "cohort": "Failed AP screen",       "target": "sphere"},
    "sphere_no_desc":  {"section": "Spherical-targeted",  "cohort": "Failed descriptor screen","target": "sphere"},
    "sphere_pepmorph": {"section": "Spherical-targeted",  "cohort": "PepMorph candidates",    "target": "sphere"},

    "fiber_no_ap":     {"section": "Fibril-targeted",     "cohort": "Failed AP screen",       "target": "fiber"},
    "fiber_no_desc":   {"section": "Fibril-targeted",     "cohort": "Failed descriptor screen","target": "fiber"},
    "fiber_pepmorph":  {"section": "Fibril-targeted",     "cohort": "PepMorph candidates",    "target": "fiber"},
}

tab = compute_descriptive_values(
    df_pep,
    ap_thresh=1.8,
    rmoi_sphere_thresh=0.75,
    rmoi_fiber_thresh=0.35,
    class_meta=class_meta,
    untargeted_mode="majority",  # or "any_run" if you want S/F to potentially overlap
)

rates, stats = compute_rates_values(
    df_pep,
    ap_thresh=1.8,
    sphere_pepmorph_class="sphere_pepmorph",
    sphere_descfail_class="sphere_no_desc",
    fiber_pepmorph_class="fiber_pepmorph",
    fiber_descfail_class="fiber_no_desc",
)

In [105]:
tab_display_cols = [
    "section", "cohort", "n_total", "n_agg", "agg_rate_str", "rmoi_outcome_str", "visual_outcome_str"
]
print(tab[tab_display_cols].to_string(index=False))

print("\n--- Table rates (success, Wilson CI) ---")
print(rates.to_string(index=False))

print("\n--- Table Fisher stats (OR, CI, p) ---")
print(stats.to_string(index=False))

           section                   cohort  n_total  n_agg   agg_rate_str                rmoi_outcome_str              visual_outcome_str
        Untargeted                   Random       15      3   20.0% (3/15)   S: 0.0% (0/3) ; F: 0.0% (0/3)   S: 0.0% (0/3) ; F: 0.0% (0/3)
        Untargeted             Unsupervised       12      7   58.3% (7/12) S: 14.3% (1/7) ; F: 57.1% (4/7) S: 14.3% (1/7) ; F: 71.4% (5/7)
Spherical-targeted         Failed AP screen       15      1    6.7% (1/15)                      0.0% (0/1)                      0.0% (0/1)
Spherical-targeted Failed descriptor screen       15     13  86.7% (13/15)                    46.2% (6/13)                    61.5% (8/13)
Spherical-targeted      PepMorph candidates       15     15 100.0% (15/15)                   73.3% (11/15)                   80.0% (12/15)
   Fibril-targeted         Failed AP screen       15      4   26.7% (4/15)                      0.0% (0/4)                     50.0% (2/4)
   Fibril-targeted Failed descriptor screen       15     13  86.7% (13/15)                    23.1% (3/13)                    46.2% (6/13)
   Fibril-targeted      PepMorph candidates       15     15 100.0% (15/15)                    26.7% (4/15)                   86.7% (13/15)

--- Table rates (success, Wilson CI) ---
    target     cohort  success_k  n     rate    ci_lo    ci_hi
   Spheres   PepMorph         12 15 0.800000 0.548146 0.929525
   Spheres Desc.-fail          8 13 0.615385 0.355229 0.822903
   Fibrils   PepMorph         13 15 0.866667 0.621180 0.962639
   Fibrils Desc.-fail          6 13 0.461538 0.232061 0.708562
All pooled   PepMorph         25 30 0.833333 0.664356 0.926635
All pooled Desc.-fail         14 26 0.538462 0.354579 0.712441

--- Table Fisher stats (OR, CI, p) ---
    target  fisher_or  or_ci_lo  or_ci_hi  p_value  pep_success  pep_n  ctrl_success  ctrl_n
   Spheres   2.500000  0.462258 13.520582 0.409662           12     15             8      13
   Fibrils   7.583333  1.197961 48.004012 0.041822           13     15             6      13
All pooled   4.285714  1.250871 14.683643 0.021801           25     30            14      26

## Visualization

In [50]:
import os
import math
import numpy as np
import pandas as pd

import MDAnalysis as mda
from MDAnalysis.lib.distances import capped_distance, minimize_vectors

from pathlib import Path
from datetime import datetime

import os, platform, warnings

warnings.filterwarnings(
    "ignore",
    message=r"Failed to use notebook backend:.*",
    category=UserWarning,
)

import pyvista as pv

pv.set_jupyter_backend(None)

if platform.system() == "Linux":
    try:
        pv.start_xvfb(wait=0.1)
    except Exception as e:
        raise RuntimeError(
            "Xvfb could not be started. Install it (e.g., apt-get install xvfb "
            "or conda-forge xorg-x11-server-xvfb) and retry."
        ) from e


from PIL import Image

from math import ceil
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.lib.units import cm

/home/go46vuw/miniconda3/lib/python3.12/site-packages/pyvista/plotting/utilities/xvfb.py:48: PyVistaDeprecationWarning: This function is deprecated and will be removed in future version of PyVista. Use vtk-osmesa instead.
  warnings.warn(

In [51]:
ROOT = Path("per_class")
CSV_PATH = Path("analysis_by_run.csv")

OUT_ROOT = Path("pdf_reports")
IMG_CACHE_DIRNAME = "_render_cache"

TOP_NAME = "peptide-cg.gro"
TRAJ_NAME = "trajout.xtc"

RUNS = ["run_1", "run_2", "run_3"]
CLASSES = [
    "random",
    "unsupervised",
    "sphere_no_ap",
    "sphere_no_desc",
    "sphere_pepmorph",
    "fiber_no_ap",
    "fiber_no_desc",
    "fiber_pepmorph",
]

FORCE_RERENDER = True
RENDER_DPI_SCALE = 0.55
WINDOW_SIZE_PX = (2200, 2200)

In [52]:
VIEW_1 = dict(degx=5, degy=100, degz=0,  order="zyx", pad=1.1)
VIEW_2 = dict(degx=5, degy=100, degz=90, order="zyx", pad=1.1)


TEAL = ['#E0F2F1', '#B2DFDB', '#4DB6AC', '#26A69A', '#00796B']
PAPER_GRAY = '#3F3F3F'
BB_COLOR = TEAL[4]
SC_COLOR = TEAL[3]

In [53]:
BB_POINT_SIZE = 8
SC_POINT_SIZE = 6

CUTOFF_NM = 1.8
MIN_PNG_BYTES = 2000

USE_FILESYSTEM = False

_PNG_MAGIC = b"\x89PNG\r\n\x1a\n"

def is_valid_png(path: Path, min_bytes=MIN_PNG_BYTES):
    try:
        path = Path(path)
        if not path.exists(): return False
        if path.stat().st_size < min_bytes: return False
        with path.open("rb") as f:
            return f.read(8) == _PNG_MAGIC
    except Exception:
        return False


def _residue_anchors(U):
    """One anchor per residue (BB if present; else residue COM). Units: Å."""
    anchors = []
    for res in U.residues:
        bb = res.atoms.select_atoms("name BB")
        anchors.append(bb.positions[0] if bb.n_atoms else res.atoms.center_of_mass())
    return np.asarray(anchors, dtype=float)

def _largest_residue_cluster_from_anchors(anchors_A, cutoff_nm, box):
    """
    anchors_A: (n,3) Å
    cutoff_nm: nm
    box: MDAnalysis ts.dimensions (Å + angles)
    """
    cutoff_A = cutoff_nm * 10.0
    pairs = capped_distance(
        anchors_A, anchors_A, cutoff_A,
        box=box, return_distances=False
    )

    n = len(anchors_A)
    parent = np.arange(n, dtype=int)

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[rb] = ra

    for i, j in pairs:
        if i != j:
            union(int(i), int(j))

    comps = {}
    for i in range(n):
        r = find(i)
        comps.setdefault(r, []).append(i)

    largest = max(comps.values(), key=len) if comps else [0]
    return np.array(largest, dtype=int)

def center_main_cluster_inplace_on_current_frame(U, cutoff_nm=CUTOFF_NM, use_bb_for_com=True):
    """
    Mutates positions of U.atoms in the current timestep:
      1) make residues in largest cluster contiguous (min image)
      2) translate cluster COM to box center (min image)
      3) wrap into primary box
    """
    box = U.dimensions.copy()
    anchors_all = _residue_anchors(U)

    cluster_res_idx = _largest_residue_cluster_from_anchors(anchors_all, cutoff_nm, box)

    idx = np.concatenate([U.residues[i].atoms.indices for i in cluster_res_idx])
    cluster = U.atoms[idx]
    com_group = cluster.select_atoms("name BB") if use_bb_for_com else cluster

    # 1) make residues contiguous near cluster COM
    com = com_group.center_of_mass()
    for ri in cluster_res_idx:
        res = U.residues[int(ri)]
        disp = res.atoms.center_of_mass() - com
        shift = minimize_vectors(disp[None, :], box=box)[0] - disp
        res.atoms.positions += shift

    # 2) translate cluster COM to box center
    com2 = com_group.center_of_mass()
    box_center = 0.5 * box[:3]
    delta = minimize_vectors((com2 - box_center)[None, :], box=box)[0]
    U.atoms.positions -= delta

    # 3) wrap
    U.atoms.pack_into_box(box=box)

def cell_vectors_from_dimensions(dim):
    """
    MDAnalysis dimensions: [a,b,c,alpha,beta,gamma]
      a,b,c in Å; angles in degrees.
    Return 3 cell vectors (Å) in Cartesian coordinates.
    """
    a, b, c, alpha, beta, gamma = dim
    alpha = math.radians(alpha)
    beta  = math.radians(beta)
    gamma = math.radians(gamma)

    va = np.array([a, 0.0, 0.0], dtype=float)
    vb = np.array([b * math.cos(gamma), b * math.sin(gamma), 0.0], dtype=float)

    cx = c * math.cos(beta)
    cy = c * (math.cos(alpha) - math.cos(beta) * math.cos(gamma)) / max(math.sin(gamma), 1e-8)
    cz_sq = c*c - cx*cx - cy*cy
    cz = math.sqrt(max(cz_sq, 0.0))
    vc = np.array([cx, cy, cz], dtype=float)

    return va, vb, vc

def unitcell_edges(va, vb, vc):
    """Edges for the parallelepiped cell."""
    o = np.array([0.0, 0.0, 0.0])
    pts = [
        o, va, vb, va+vb,
        vc, va+vc, vb+vc, va+vb+vc
    ]
    edges_idx = [
        (0,1),(0,2),(1,3),(2,3),
        (4,5),(4,6),(5,7),(6,7),
        (0,4),(1,5),(2,6),(3,7)
    ]
    return [(pts[i], pts[j]) for i, j in edges_idx]

def quat_axis_angle(axis, deg):
    ax, ay, az = axis
    n = (ax*ax + ay*ay + az*az)**0.5 or 1.0
    ax, ay, az = ax/n, ay/n, az/n
    th = math.radians(deg) * 0.5
    s = math.sin(th)
    return [ax*s, ay*s, az*s, math.cos(th)]

def quat_euler(degx=0.0, degy=0.0, degz=0.0, order="zyx"):
    def qmul(q2, q1):
        x1,y1,z1,w1 = q1
        x2,y2,z2,w2 = q2
        return [
            w2*x1 + x2*w1 + y2*z1 - z2*y1,
            w2*y1 - x2*z1 + y2*w1 + z2*x1,
            w2*z1 + x2*y1 - y2*x1 + z2*w1,
            w2*w1 - x2*x1 - y2*y1 - z2*z1
        ]
    qx = quat_axis_angle([1,0,0], degx)
    qy = quat_axis_angle([0,1,0], degy)
    qz = quat_axis_angle([0,0,1], degz)
    q  = [0,0,0,1]
    for c in order.lower():
        q = qmul({'x': qx, 'y': qy, 'z': qz}[c], q)
    return q

def quat_to_rotmat(q):
    x,y,z,w = q
    xx, yy, zz = x*x, y*y, z*z
    xy, xz, yz = x*y, x*z, y*z
    wx, wy, wz = w*x, w*y, w*z
    return np.array([
        [1-2*(yy+zz), 2*(xy-wz),   2*(xz+wy)],
        [2*(xy+wz),   1-2*(xx+zz), 2*(yz-wx)],
        [2*(xz-wy),   2*(yz+wx),   1-2*(xx+yy)]
    ], dtype=float)


def render_two_groups_pyvista(bb_pos, sc_pos, dims, out_png: Path, view_params,
                             bb_color=BB_COLOR, sc_color=SC_COLOR, line_color=PAPER_GRAY,
                             bb_point_size=BB_POINT_SIZE, sc_point_size=SC_POINT_SIZE,
                             window_size_px=WINDOW_SIZE_PX, dpi_scale=RENDER_DPI_SCALE):
    out_png = Path(out_png)
    out_png.parent.mkdir(parents=True, exist_ok=True)

    w, h = window_size_px
    w = int(w * dpi_scale)
    h = int(h * dpi_scale)

    pl = pv.Plotter(off_screen=False, window_size=(w, h))
    pl.set_background("white")
    pl.disable_anti_aliasing()
    
    if bb_pos is not None and len(bb_pos) > 0:
        bb = pv.PolyData(bb_pos)
        pl.add_mesh(bb, color=bb_color, opacity=0.98,
                    render_points_as_spheres=True, point_size=bb_point_size)

    if sc_pos is not None and len(sc_pos) > 0:
        sc = pv.PolyData(sc_pos)
        pl.add_mesh(sc, color=sc_color, opacity=0.9,
                    render_points_as_spheres=True, point_size=sc_point_size)

    va, vb, vc = cell_vectors_from_dimensions(dims)
    for p0, p1 in unitcell_edges(va, vb, vc):
        pl.add_mesh(pv.Line(p0, p1), color=line_color, line_width=2)

    pl.camera.parallel_projection = True

    if "cam_dir" in view_params:
        cam_dir = np.asarray(view_params["cam_dir"], float)
        cam_up  = np.asarray(view_params.get("cam_up", safe_up_for(cam_dir)), float)
    else:
        q = quat_euler(view_params["degx"], view_params["degy"], view_params["degz"], view_params["order"])
        R = quat_to_rotmat(q)
        cam_dir = R @ np.array([0.0, 0.0, 1.0])
        cam_up  = R @ np.array([0.0, 1.0, 0.0])


    box_center = 0.5 * (va + vb + vc)
    # Camera axes
    cam_dir = cam_dir / (np.linalg.norm(cam_dir) + 1e-12)
    cam_up  = cam_up  / (np.linalg.norm(cam_up)  + 1e-12)
    cam_right = np.cross(cam_dir, cam_up)
    cam_right = cam_right / (np.linalg.norm(cam_right) + 1e-12)

    # Focus on the aggregate (not the box)
    pts = []
    if bb_pos is not None and len(bb_pos) > 0: pts.append(bb_pos)
    if sc_pos is not None and len(sc_pos) > 0: pts.append(sc_pos)
    pts = np.vstack(pts) if len(pts) else np.zeros((1,3), dtype=float)

    focal = pts.mean(axis=0)

    # Orthographic scale: project onto camera plane and fit tightly
    rel = pts - focal
    x = rel @ cam_right
    y = rel @ cam_up
    half_span = float(max(np.max(np.abs(x)), np.max(np.abs(y)), 1.0))  # Å

    # pad factor: >1 means zoom OUT slightly; <1 means zoom IN
    pad = float(view_params.get("pad", 1.12))  # default: small margin
    pl.camera.parallel_scale = half_span * pad

    # Distance is irrelevant for ortho size, but keep it reasonable for clipping
    dist = 8.0 * half_span
    pl.camera.position = (focal + cam_dir * dist).tolist()
    pl.camera.focal_point = focal.tolist()
    pl.camera.up = cam_up.tolist()

    # Save without producing notebook output
    pl.show(screenshot=str(out_png), interactive=False, auto_close=True)

    if not is_valid_png(out_png):
        raise RuntimeError(f"Screenshot failed or invalid PNG: {out_png}")
    
def principal_axes(pts):
    """
    pts: (N,3) array in Å.
    Returns (axes, evals) where axes[:,0] is the longest-axis direction.
    """
    pts = np.asarray(pts, float)
    c = pts.mean(axis=0, keepdims=True)
    X = pts - c
    C = (X.T @ X) / max(len(X), 1)   # covariance-ish
    evals, evecs = np.linalg.eigh(C) # ascending
    order = np.argsort(evals)[::-1]  # descending
    evals = evals[order]
    evecs = evecs[:, order]          # columns are axes
    # normalize (just in case)
    evecs = evecs / (np.linalg.norm(evecs, axis=0, keepdims=True) + 1e-12)
    return evecs, evals

def safe_up_for(cam_dir, preferred=np.array([0.0, 1.0, 0.0])):
    cam_dir = np.asarray(cam_dir, float)
    cam_dir = cam_dir / (np.linalg.norm(cam_dir) + 1e-12)
    up = preferred.copy()
    # if nearly parallel, switch preferred
    if abs(np.dot(cam_dir, up)) > 0.92:
        up = np.array([1.0, 0.0, 0.0])
    # orthonormalize
    up = up - np.dot(up, cam_dir) * cam_dir
    up = up / (np.linalg.norm(up) + 1e-12)
    return up

def render_two_views_for_peptide(peptide_dir: Path, out_png1: Path, out_png2: Path, cutoff_nm=CUTOFF_NM):
    top = peptide_dir / TOP_NAME
    traj = peptide_dir / TRAJ_NAME
    if not top.exists() or not traj.exists():
        raise FileNotFoundError(f"Missing {TOP_NAME} or {TRAJ_NAME} in {peptide_dir}")

    u = mda.Universe(str(top), str(traj))
    u.trajectory[-1]  # last frame
    center_main_cluster_inplace_on_current_frame(u, cutoff_nm=cutoff_nm)

    dims = u.dimensions.copy()
    bb_pos = u.atoms.select_atoms("name BB").positions.copy()
    sc_pos = u.atoms.select_atoms("not name BB").positions.copy()

    pts = np.vstack([bb_pos, sc_pos]) if (len(bb_pos) and len(sc_pos)) else (bb_pos if len(bb_pos) else sc_pos)

    axes, evals = principal_axes(pts)
    a1 = axes[:, 0]
    a2 = axes[:, 1]
    a3 = axes[:, 2]

    anis = float(evals[0] / max(evals[1], 1e-12))

    if anis > 1.35:
        V1 = dict(cam_dir=a3, cam_up=safe_up_for(a3, preferred=a2), pad=VIEW_1.get("pad", 1.05))
        V2 = dict(cam_dir=a2, cam_up=safe_up_for(a2, preferred=a1), pad=VIEW_2.get("pad", 1.05))
    else:
        V1 = VIEW_1
        V2 = VIEW_2

    render_two_groups_pyvista(bb_pos, sc_pos, dims, out_png1, V1)
    render_two_groups_pyvista(bb_pos, sc_pos, dims, out_png2, V2)



def png_to_jpeg(png_path: Path, jpg_path: Path, quality=75, max_px=1400):
    """
    Convert to JPEG and optionally downscale so the largest side is max_px.
    """
    png_path = Path(png_path)
    jpg_path = Path(jpg_path)
    jpg_path.parent.mkdir(parents=True, exist_ok=True)

    im = Image.open(png_path).convert("RGB")
    w, h = im.size
    m = max(w, h)
    if m > max_px:
        scale = max_px / m
        im = im.resize((int(w*scale), int(h*scale)), Image.Resampling.LANCZOS)

    im.save(jpg_path, "JPEG", quality=quality, optimize=True, progressive=True)
    return jpg_path

def build_group_pdf_onepage(entries, out_pdf: Path, title: str, subtitle: str = "",
                            max_cols: int = 3,
                            margin_cm: float = 0.7,
                            gutter_cm: float = 0.28,
                            inner_gutter_cm: float = 0.18,
                            caption_fs: int = 8,
                            header_fs: int = 12,
                            subtitle_fs: int = 8):
    """
    Single-page portrait contact sheet:
      - grid of peptides (<= max_cols columns)
      - each tile: caption + two views
    """
    out_pdf = Path(out_pdf)
    out_pdf.parent.mkdir(parents=True, exist_ok=True)

    page_w, page_h = A4
    page_h = page_h - 3*cm
    c = canvas.Canvas(str(out_pdf), pagesize=(page_w, page_h))

    margin = margin_cm * cm
    gutter = gutter_cm * cm
    inner_gutter = inner_gutter_cm * cm

    # Header height (kept compact)
    header_h = 0.8 * cm if (title or subtitle) else 0.0

    usable_w = page_w - 2 * margin
    usable_h = page_h - 2 * margin - header_h

    n = len(entries)
    if n == 0:
        c.setFont("Helvetica-Bold", header_fs)
        c.drawString(margin, page_h - margin, title or "Empty group")
        c.setFont("Helvetica", subtitle_fs)
        c.drawString(margin, page_h - margin - 0.8*cm, "No peptides found.")
        c.save()
        return

    # Fixed max 3 columns; choose cols based on count
    cols = min(max_cols, 3)
    if n <= 2: cols = n
    elif n <= 6: cols = min(2, cols)

    rows = int(ceil(n / cols))

    tile_w = (usable_w - (cols - 1) * gutter) / cols
    tile_h = (usable_h - (rows - 1) * gutter) / rows

    # Caption band
    cap_h = 0.55 * cm  # bigger than before

    # Header
    y_top = page_h - margin
    if header_h > 0:
        c.setFont("Helvetica-Bold", header_fs)
        c.drawString(margin, y_top, title)
        if subtitle:
            c.setFont("Helvetica", subtitle_fs)
            c.drawString(margin, y_top - 0.60*cm, subtitle)

    grid_top = page_h - margin - header_h

    def draw_placeholder(x, y, w, h, text="missing"):
        c.rect(x, y, w, h, stroke=1, fill=0)
        c.setFont("Helvetica", max(7, caption_fs - 1))
        c.drawString(x + 0.15*cm, y + h - 0.45*cm, text)

    # Sort so the grid is meaningful (AP desc, then RMOI desc)
    def sort_key(e):
        ap = e.get("ap"); rm = e.get("rmoi")
        apk = ap if ap is not None else -1e18
        rmk = rm if rm is not None else -1e18
        return (-apk, -rmk, str(e.get("peptide","")))

    entries_sorted = sorted(entries, key=sort_key)

    for idx, e in enumerate(entries_sorted):
        r = idx // cols
        col = idx % cols

        tx = margin + col * (tile_w + gutter)
        ty_top = grid_top - r * (tile_h + gutter)
        ty = ty_top - tile_h

        # Caption (larger)
        peptide = str(e.get("peptide", "NA"))
        ap = e.get("ap"); rm = e.get("rmoi")
        cap = f"{peptide} | AP: {(f'{ap:.3f}' if ap is not None else 'NA')} | RMOI: {(f'{rm:.3f}' if rm is not None else 'NA')}"
        c.setFont("Helvetica", caption_fs)
        c.drawString(tx + 0.05*cm, ty_top - 0.45*cm, cap[:120])

        # Image area (use as much of tile as possible)
        img_area_h = tile_h - cap_h
        img_w = (tile_w - inner_gutter) / 2.0
        img_h = img_area_h

        img_y = ty
        img1 = Path(e.get("img1_path") or "")
        img2 = Path(e.get("img2_path") or "")

        def draw_img(path: Path, x, y, w, h):
            if (not path.exists()) or (path.stat().st_size < MIN_PNG_BYTES):
                draw_placeholder(x, y, w, h, "render failed")
                return
            try:
                jpg_path = Path(str(path)).with_suffix(".jpg")
                if (not jpg_path.exists()) or jpg_path.stat().st_mtime < path.stat().st_mtime:
                    png_to_jpeg(path, jpg_path, quality=75, max_px=1200)
                ir = ImageReader(str(jpg_path))
                # Fill the allocated box (minimal letterboxing)
                c.drawImage(ir, x, y, width=w, height=h, preserveAspectRatio=True, anchor='c', mask="auto")
            except Exception:
                draw_placeholder(x, y, w, h, "bad image")

        draw_img(img1, tx,                    img_y, img_w, img_h)
        draw_img(img2, tx + img_w + inner_gutter, img_y, img_w, img_h)

        # Tile outline (optional but helps scanning)
        c.setLineWidth(0.4)
        c.rect(tx, ty, tile_w, tile_h, stroke=1, fill=0)

    c.save()

In [54]:
merged_by_run = pd.read_csv(CSV_PATH)

for col in ["peptide", "class", "run", "aggregation_propensity", "RMOI"]:
    if col not in merged_by_run.columns:
        raise ValueError(f"CSV missing required column: {col}")

merged_by_run["aggregation_propensity"] = pd.to_numeric(merged_by_run["aggregation_propensity"], errors="coerce")
merged_by_run["RMOI"] = pd.to_numeric(merged_by_run["RMOI"], errors="coerce")

if CLASSES is None:
    CLASSES = sorted(merged_by_run["class"].dropna().unique().tolist())

print("Runs:", RUNS)
print("Classes:", CLASSES)

Runs: ['run_1', 'run_2', 'run_3']
Classes: ['random', 'unsupervised', 'sphere_no_ap', 'sphere_no_desc', 'sphere_pepmorph', 'fiber_no_ap', 'fiber_no_desc', 'fiber_pepmorph']

In [55]:
OUT_ROOT.mkdir(parents=True, exist_ok=True)

def peptide_dir_for(run: str, cls: str, peptide: str) -> Path:
    return ROOT / run / cls / peptide

def cache_paths(peptide_dir: Path):
    cache_dir = peptide_dir / IMG_CACHE_DIRNAME
    return cache_dir / "view_1.png", cache_dir / "view_2.png"

def ensure_two_views(peptide_dir: Path, force=False):
    img1, img2 = cache_paths(peptide_dir)

    if (not force) and is_valid_png(img1) and is_valid_png(img2):
        return img1, img2

    # Always (re)create cache dir
    img1.parent.mkdir(parents=True, exist_ok=True)

    # Render deterministically with PyVista
    render_two_views_for_peptide(peptide_dir, img1, img2, cutoff_nm=CUTOFF_NM)
    return img1, img2

def get_peptides_for_group(run, cls):
    if USE_FILESYSTEM:
        base = ROOT / run / cls
        if not base.exists():
            return []
        return sorted([p.name for p in base.iterdir() if p.is_dir()])
    else:
        df = merged_by_run[(merged_by_run["run"] == run) & (merged_by_run["class"] == cls)]
        return df["peptide"].dropna().astype(str).unique().tolist()

In [58]:
summary = []

for run in RUNS:
    for cls in CLASSES:
        df = merged_by_run[(merged_by_run["run"] == run) & (merged_by_run["class"] == cls)].copy()
        peptides = get_peptides_for_group(run, cls)

        entries = []
        print(f"\n=== {run} | {cls} | peptides={len(peptides)} ===")

        for pep in peptides:
            pdir = peptide_dir_for(run, cls, pep)

            ap = None
            rm = None
            if not df.empty and (df["peptide"] == pep).any():
                row = df.loc[df["peptide"] == pep].iloc[0]
                ap = float(row["aggregation_propensity"]) if pd.notna(row["aggregation_propensity"]) else None
                rm = float(row["RMOI"]) if pd.notna(row["RMOI"]) else None

            img1 = img2 = None
            try:
                if pdir.exists():
                    img1, img2 = ensure_two_views(pdir, force=FORCE_RERENDER)
                else:
                    print(f"  [WARN] Missing directory: {pdir}")
            except Exception as ex:
                print(f"  [WARN] Render failed for {pep} ({pdir}): {ex}")

            entries.append(dict(
                peptide=pep,
                ap=ap,
                rmoi=rm,
                img1_path=str(img1) if img1 else None,
                img2_path=str(img2) if img2 else None,
            ))

        section = SECTION_LABEL.get(cls, cls)
        cohort  = COHORT_LABEL.get(cls, cls)

        safe_name = cls
        out_pdf = OUT_ROOT / run / f"{safe_name}.pdf"

        build_group_pdf_onepage(
            entries,
            out_pdf,
            title=f"{run} | {section} | {cohort}",
            # subtitle="Two orthographic views; last frame; centered main cluster",
            max_cols=3,
            caption_fs=8,
            header_fs =12,
            subtitle_fs= 8,
        )
        
        summary.append((run, cls, len(entries), str(out_pdf)))

print("\nDone. PDFs written:")
for run, cls, n, path in summary:
    print(f"  {run:>5} | {cls:<20} | peptides={n:4d} | {path}")

=== run_1 | random | peptides=15 ===

=== run_1 | unsupervised | peptides=12 ===

=== run_1 | sphere_no_ap | peptides=15 ===

=== run_1 | sphere_no_desc | peptides=15 ===

=== run_1 | sphere_pepmorph | peptides=15 ===

=== run_1 | fiber_no_ap | peptides=15 ===

=== run_1 | fiber_no_desc | peptides=15 ===

=== run_1 | fiber_pepmorph | peptides=15 ===

=== run_2 | random | peptides=15 ===

=== run_2 | unsupervised | peptides=12 ===

=== run_2 | sphere_no_ap | peptides=15 ===

=== run_2 | sphere_no_desc | peptides=15 ===

=== run_2 | sphere_pepmorph | peptides=15 ===

=== run_2 | fiber_no_ap | peptides=15 ===

=== run_2 | fiber_no_desc | peptides=15 ===

=== run_2 | fiber_pepmorph | peptides=15 ===

=== run_3 | random | peptides=15 ===

=== run_3 | unsupervised | peptides=12 ===

=== run_3 | sphere_no_ap | peptides=15 ===

=== run_3 | sphere_no_desc | peptides=15 ===

=== run_3 | sphere_pepmorph | peptides=15 ===

=== run_3 | fiber_no_ap | peptides=15 ===

=== run_3 | fiber_no_desc | peptides=15 ===

=== run_3 | fiber_pepmorph | peptides=15 ===

Done. PDFs written:
  run_1 | random               | peptides=  15 | pdf_reports/run_1/random.pdf
  run_1 | unsupervised         | peptides=  12 | pdf_reports/run_1/unsupervised.pdf
  run_1 | sphere_no_ap         | peptides=  15 | pdf_reports/run_1/sphere_no_ap.pdf
  run_1 | sphere_no_desc       | peptides=  15 | pdf_reports/run_1/sphere_no_desc.pdf
  run_1 | sphere_pepmorph      | peptides=  15 | pdf_reports/run_1/sphere_pepmorph.pdf
  run_1 | fiber_no_ap          | peptides=  15 | pdf_reports/run_1/fiber_no_ap.pdf
  run_1 | fiber_no_desc        | peptides=  15 | pdf_reports/run_1/fiber_no_desc.pdf
  run_1 | fiber_pepmorph       | peptides=  15 | pdf_reports/run_1/fiber_pepmorph.pdf
  run_2 | random               | peptides=  15 | pdf_reports/run_2/random.pdf
  run_2 | unsupervised         | peptides=  12 | pdf_reports/run_2/unsupervised.pdf
  run_2 | sphere_no_ap         | peptides=  15 | pdf_reports/run_2/sphere_no_ap.pdf
  run_2 | sphere_no_desc       | peptides=  15 | pdf_reports/run_2/sphere_no_desc.pdf
  run_2 | sphere_pepmorph      | peptides=  15 | pdf_reports/run_2/sphere_pepmorph.pdf
  run_2 | fiber_no_ap          | peptides=  15 | pdf_reports/run_2/fiber_no_ap.pdf
  run_2 | fiber_no_desc        | peptides=  15 | pdf_reports/run_2/fiber_no_desc.pdf
  run_2 | fiber_pepmorph       | peptides=  15 | pdf_reports/run_2/fiber_pepmorph.pdf
  run_3 | random               | peptides=  15 | pdf_reports/run_3/random.pdf
  run_3 | unsupervised         | peptides=  12 | pdf_reports/run_3/unsupervised.pdf
  run_3 | sphere_no_ap         | peptides=  15 | pdf_reports/run_3/sphere_no_ap.pdf
  run_3 | sphere_no_desc       | peptides=  15 | pdf_reports/run_3/sphere_no_desc.pdf
  run_3 | sphere_pepmorph      | peptides=  15 | pdf_reports/run_3/sphere_pepmorph.pdf
  run_3 | fiber_no_ap          | peptides=  15 | pdf_reports/run_3/fiber_no_ap.pdf
  run_3 | fiber_no_desc        | peptides=  15 | pdf_reports/run_3/fiber_no_desc.pdf
  run_3 | fiber_pepmorph       | peptides=  15 | pdf_reports/run_3/fiber_pepmorph.pdf