In [50]:
import pandas as pd
import numpy as np

# there are 3 files, generated_fibers_init.txt, filtered_ap_peptides_fiber.txt and valid_fibers.csv
# these all correspond to the same set of fibers, but only with the ones passing each filtering step
# we want to know which fibers did not pass each filtering step

np.random.seed(42)

fibers_init = pd.read_csv('generated_fibers_init.txt', header=None, names=['fiber_id'])
fibers_init = fibers_init.drop_duplicates()
fibers_filtered_ap = pd.read_csv('filtered_ap_peptides_fiber.txt', header=None, names=['fiber_id', 'fiber_id_3', 'ap', 'agg_prob'])
fibers_valid = pd.read_csv('valid_fibers.csv', header=0, names=['fiber_id'])

In [51]:
# find fibers that did not pass the AP peptide filtering step
fibers_not_passing_ap = fibers_init[~fibers_init['fiber_id'].isin(fibers_filtered_ap['fiber_id'])]
fibers_not_passing_ap

        fiber_id
2        KIETGFE
8        AYHYGPD
10       IRFAGEV
13       PEFPDYH
14      DHVEFFIC
...          ...
4766  FFSTNGNAYT
4775  LTFNAGLTCR
4779  QLNPGQWPPL
4783  AYQWQANVYP
4794   ISVEPRIVS

[1006 rows x 1 columns]

In [52]:
# find fibers that did not pass the final validation step
fibers_not_passing_valid = fibers_filtered_ap[~fibers_filtered_ap['fiber_id'].isin(fibers_valid['fiber_id'])]
fibers_not_passing_valid

        fiber_id                                fiber_id_3        ap  agg_prob
0       ALWYVFPE           Ala-Leu-Trp-Tyr-Val-Phe-Pro-Glu  0.475453  0.997710
1      AVRADYVYC       Ala-Val-Arg-Ala-Asp-Tyr-Val-Tyr-Cys  0.470284  0.998530
2     VPVFLPEAIF   Val-Pro-Val-Phe-Leu-Pro-Glu-Ala-Ile-Phe  0.515673  0.999817
3     PVFDGTALHC   Pro-Val-Phe-Asp-Gly-Thr-Ala-Leu-His-Cys  0.431203  0.977304
4      KGFSYEQYC       Lys-Gly-Phe-Ser-Tyr-Glu-Gln-Tyr-Cys  0.452127  0.991674
...          ...                                       ...       ...       ...
3789   RVCNYVAFW       Arg-Val-Cys-Asn-Tyr-Val-Ala-Phe-Trp  0.506668  0.999832
3790     LGCFQKY               Leu-Gly-Cys-Phe-Gln-Lys-Tyr  0.467938  0.986392
3791    KYFEAGFH           Lys-Tyr-Phe-Glu-Ala-Gly-Phe-His  0.467795  0.997916
3792  NASSLQPWVW   Asn-Ala-Ser-Ser-Leu-Gln-Pro-Trp-Val-Trp  0.469642  0.998846
3793  FPVIIVVVPV   Phe-Pro-Val-Ile-Ile-Val-Val-Val-Pro-Val  0.564234  0.999889

[3765 rows x 4 columns]

In [53]:
len(fibers_init) - len(fibers_not_passing_ap) - len(fibers_not_passing_valid) == len(fibers_valid)

True

In [54]:
fibers_valid

      fiber_id
0   QCVSPHWPAP
1   AIVFPGTFHQ
2   CQCTAGCYVW
3   QYWCPGMAIC
4   PAPFPWSIWI
5   PFAIPYCSTP
6   LICWTGHCHH
7    LDIYNHPFF
8   RCVQGGHPFC
9   AFLWNGISYQ
10  PVWRADSWHC
11  TYPFANGVIH
12  PFLFAGDVHM
13  CVSAPGIFHC
14  ILSCPGWPFY
15  TMQYDNWSLH
16  FAHHNGCVFE
17   RIIAGYDVV
18  RAVYGDFVFL
19  QIRTYDFLVF
20  VFLVPVDFKY
21  ILSFPDKVTY
22  FTFIPGWVDL
23  VVVDNQWSFK
24  PVFCADQWFC
25  LFLTADSYCF
26  HYVSGRFLIY
27  PALMPGETWY
28  ALVDDKYFFI

In [55]:
# do the same for the spheres
spheres_init = pd.read_csv('generated_spheres_init.txt', header=None, names=['sphere_id'])
spheres_init = spheres_init.drop_duplicates()
filtered_ap_spheres = pd.read_csv('filtered_ap_peptides_spheres.txt', header=None, names=['sphere_id', 'sphere_id_3', 'ap', 'agg_prob'])
spheres_valid = pd.read_csv('valid_spheres.csv', header=0, names=['sphere_id'])

In [56]:
spheres_not_passing_ap = spheres_init[~spheres_init['sphere_id'].isin(filtered_ap_spheres['sphere_id'])]
spheres_not_passing_ap

     sphere_id
0         PFQD
1         WAIE
3         VDWA
7         YRED
8         FKED
...        ...
4785   LQRRDII
4790   LREHPDR
4791   CADRRIT
4796   RDMRIHD
4797   RYANECT

[711 rows x 1 columns]

In [57]:
spheres_not_passing_valid = filtered_ap_spheres[~filtered_ap_spheres['sphere_id'].isin(spheres_valid['sphere_id'])]
spheres_not_passing_valid

     sphere_id                   sphere_id_3        ap  agg_prob
0        FVCIT           Phe-Val-Cys-Ile-Thr  0.638266  0.999973
1        CYTEW           Cys-Tyr-Thr-Glu-Trp  0.500524  0.999701
2       QLYQVL       Gln-Leu-Tyr-Gln-Val-Leu  0.474885  0.983154
3        IPLMV           Ile-Pro-Leu-Met-Val  0.564286  0.998857
4        WAIFF           Trp-Ala-Ile-Phe-Phe  0.669504  1.000000
...        ...                           ...       ...       ...
3981      FCII               Phe-Cys-Ile-Ile  0.613826  0.999893
3982   FWAQMIV   Phe-Trp-Ala-Gln-Met-Ile-Val  0.548479  0.999676
3983    FMFIDW       Phe-Met-Phe-Ile-Asp-Trp  0.617533  0.999998
3984   LWVLFIF   Leu-Trp-Val-Leu-Phe-Ile-Phe  0.632838  0.999999
3985    WLFLWG       Trp-Leu-Phe-Leu-Trp-Gly  0.632588  1.000000

[3922 rows x 4 columns]

In [58]:
len(spheres_init) - len(spheres_not_passing_ap) - len(spheres_not_passing_valid) == len(spheres_valid)

True

In [59]:
spheres_valid

   sphere_id
0     IFFFII
1    IFLFIFV
2     FFIFFI
3     FLFIII
4    IWIFIII
..       ...
59   LIIIIVW
60   IFFFILV
61    WIIIIV
62    FFIIVI
63    IWFIII

[64 rows x 1 columns]

In [60]:
fibers_neg_control_ap = fibers_not_passing_ap.sample(n=15, random_state=42)
spheres_neg_control_ap = spheres_not_passing_ap.sample(n=15, random_state=42)
fibers_neg_control_valid = fibers_not_passing_valid.sample(n=15, random_state=42)
spheres_neg_control_valid = spheres_not_passing_valid.sample(n=15, random_state=42)

# merge into a single dataframe, instead of 'fiber_id' or 'sphere_id' use 'structure_id' and add a column 'structure_type' with values 'fiber' or 'sphere'
neg_control_ap = pd.concat([
    fibers_neg_control_ap.rename(columns={'fiber_id': 'structure_id', 'fiber_id_3': 'structure_id_3'}).assign(structure_type='fiber'),
    spheres_neg_control_ap.rename(columns={'sphere_id': 'structure_id', 'sphere_id_3': 'structure_id_3'}).assign(structure_type='sphere')
])

neg_control_valid = pd.concat([
    fibers_neg_control_valid.rename(columns={'fiber_id': 'structure_id', 'fiber_id_3': 'structure_id_3'}).assign(structure_type='fiber'),
    spheres_neg_control_valid.rename(columns={'sphere_id': 'structure_id', 'sphere_id_3': 'structure_id_3'}).assign(structure_type='sphere')
])

# merge both neg control dataframes
neg_control = pd.concat([neg_control_ap, neg_control_valid])
neg_control.reset_index(drop=True, inplace=True)
neg_control

,structure_id,structure_type,structure_id_3,ap,agg_prob
0,EFAHHYNQIL,fiber,NaN,NaN,NaN
1,VSVQPMECH,fiber,NaN,NaN,NaN
2,LYRPAPLEL,fiber,NaN,NaN,NaN
3,LQICQWAA,fiber,NaN,NaN,NaN
4,DAPFIMAY,fiber,NaN,NaN,NaN
5,LCPDSILVN,fiber,NaN,NaN,NaN
6,GPCIDQCSF,fiber,NaN,NaN,NaN
7,HALNGGTW,fiber,NaN,NaN,NaN
8,VYHEIDGFK,fiber,NaN,NaN,NaN
9,AWIRYDE,fiber,NaN,NaN,NaN
10,PEPFLNKTVM,fiber,NaN,NaN,NaN
11,EVLLAHAW,fiber,NaN,NaN,NaN
12,QVLGQWSLP,fiber,NaN,NaN,NaN
13,KTKEWHHE,fiber,NaN,NaN,NaN
14,KVLGDNPW,fiber,NaN,NaN,NaN
15,ERIRED,sphere,NaN,NaN,NaN
16,VCDVI,sphere,NaN,NaN,NaN
17,ELVM,sphere,NaN,NaN,NaN
18,PEHR,sphere,NaN,NaN,NaN
19,CEESFR,sphere,NaN,NaN,NaN
20,VEMASH,sphere,NaN,NaN,NaN
21,QDRE,sphere,NaN,NaN,NaN
22,EAYR,sphere,NaN,NaN,NaN
23,MMDY,sphere,NaN,NaN,NaN
24,LFRQEE,sphere,NaN,NaN,NaN
25,MGNV,sphere,NaN,NaN,NaN
26,AYID,sphere,NaN,NaN,NaN
27,DWNH,sphere,NaN,NaN,NaN
28,VMAIVIE,sphere,NaN,NaN,NaN
29,RKEPIE,sphere,NaN,NaN,NaN
30,PNVVYQVWYT,fiber,Pro-Asn-Val-Val-Tyr-Gln-Val-Trp-Tyr-Thr,0.494724,0.999875
31,IFCLIRSYLM,fiber,Ile-Phe-Cys-Leu-Ile-Arg-Ser-Tyr-Leu-Met,0.510839,0.999926
32,RLSHNAMLY,fiber,Arg-Leu-Ser-His-Asn-Ala-Met-Leu-Tyr,0.441413,0.988917
33,WEFTGVNFT,fiber,Trp-Glu-Phe-Thr-Gly-Val-Asn-Phe-Thr,0.454921,0.992383
34,LEYGFYCV,fiber,Leu-Glu-Tyr-Gly-Phe-Tyr-Cys-Val,0.512835,0.999760
35,FVHIVNDQVV,fiber,Phe-Val-His-Ile-Val-Asn-Asp-Gln-Val-Val,0.437295,0.987502
36,PPFAQPMW,fiber,Pro-Pro-Phe-Ala-Gln-Pro-Met-Trp,0.511118,0.999560
37,LFLIACTPY,fiber,Leu-Phe-Leu-Ile-Ala-Cys-Thr-Pro-Tyr,0.541212,0.999937
38,WRWSDGCIL,fiber,Trp-Arg-Trp-Ser-Asp-Gly-Cys-Ile-Leu,0.486403,0.999381
39,VFESFTPY,fiber,Val-Phe-Glu-Ser-Phe-Thr-Pro-Tyr,0.563001,0.999969
40,TLAGIRWVTE,fiber,Thr-Leu-Ala-Gly-Ile-Arg-Trp-Val-Thr-Glu,0.431976,0.919771
41,PFVCLIVF,fiber,Pro-Phe-Val-Cys-Leu-Ile-Val-Phe,0.632314,0.999997
42,FIRSESFL,fiber,Phe-Ile-Arg-Ser-Glu-Ser-Phe-Leu,0.511274,0.998690
43,PVFVIVVFP,fiber,Pro-Val-Phe-Val-Ile-Val-Val-Phe-Pro,0.636027,0.999998
44,FPVSYAIY,fiber,Phe-Pro-Val-Ser-Tyr-Ala-Ile-Tyr,0.571085,0.999997
45,VIFDF,sphere,Val-Ile-Phe-Asp-Phe,0.579079,0.999942
46,WWVWE,sphere,Trp-Trp-Val-Trp-Glu,0.514255,0.999820
47,WFFWFW,sphere,Trp-Phe-Phe-Trp-Phe-Trp,0.575281,0.999999
48,CFMVAVF,sphere,Cys-Phe-Met-Val-Ala-Val-Phe,0.602417,0.999971
49,WAVFGVD,sphere,Trp-Ala-Val-Phe-Gly-Val-Asp,0.514721,0.999238
50,FYFIL,sphere,Phe-Tyr-Phe-Ile-Leu,0.643787,0.999999
51,WAIEF,sphere,Trp-Ala-Ile-Glu-Phe,0.557108,0.999842
52,HASV,sphere,His-Ala-Ser-Val,0.501225,0.998187
53,CHGLICA,sphere,Cys-His-Gly-Leu-Ile-Cys-Ala,0.444924,0.976472
54,LFVILP,sphere,Leu-Phe-Val-Ile-Leu-Pro,0.643863,0.999979
55,FACWV,sphere,Phe-Ala-Cys-Trp-Val,0.663913,0.999999
56,CMLWM,sphere,Cys-Met-Leu-Trp-Met,0.604330,0.999941
57,VLWYIWI,sphere,Val-Leu-Trp-Tyr-Ile-Trp-Ile,0.602887,0.999999
58,WMAHA,sphere,Trp-Met-Ala-His-Ala,0.500076,0.999284
59,LVIEFF,sphere,Leu-Val-Ile-Glu-Phe-Phe,0.586371,0.999942

In [61]:
# count how many sequences with len < 5 are in the neg_control, and for which type
# if it's NaN in ap or agg_prob, then it did not pass the ap filtering step
# if it's not, it did not pass the final validation step
# check how many are from each step
neg_control['sequence_length'] = neg_control['structure_id'].apply(len)
neg_control_short_seqs_ap = neg_control[(neg_control['sequence_length'] < 5) & (neg_control['ap'].isna())]
neg_control_short_seqs_valid = neg_control[(neg_control['sequence_length'] < 5) & (neg_control['ap'].notna())]

neg_control_short_seqs_ap, neg_control_short_seqs_valid

(   structure_id structure_type structure_id_3  ap  agg_prob  sequence_length
 17         ELVM         sphere            NaN NaN       NaN                4
 18         PEHR         sphere            NaN NaN       NaN                4
 21         QDRE         sphere            NaN NaN       NaN                4
 22         EAYR         sphere            NaN NaN       NaN                4
 23         MMDY         sphere            NaN NaN       NaN                4
 25         MGNV         sphere            NaN NaN       NaN                4
 26         AYID         sphere            NaN NaN       NaN                4
 27         DWNH         sphere            NaN NaN       NaN                4,
    structure_id structure_type    structure_id_3        ap  agg_prob  \
 52         HASV         sphere   His-Ala-Ser-Val  0.501225  0.998187

     sequence_length
 52                4  )

In [62]:
# sample structures with len >= 5 as substitutes for these len < 5 sequences
# from spheres_not_passing_ap if ap is NaN, else from spheres_not_passing_valid
neg_control_ap_substitutes = spheres_not_passing_ap[spheres_not_passing_ap['sphere_id'].apply(len) >= 5].sample(n=len(neg_control_short_seqs_ap), random_state=42)
neg_control_valid_substitutes = spheres_not_passing_valid[spheres_not_passing_valid['sphere_id'].apply(len) >= 5].sample(n=len(neg_control_short_seqs_valid), random_state=42)
# add missing columns to match neg_control
neg_control_ap_substitutes, neg_control_valid_substitutes

(     sphere_id
 3632   REMNSFE
 1485     VEFAV
 3885   MIVDCVL
 3876   PLVEILG
 2323     ERWDK
 2617    QWHECK
 3561    IRDYKE
 1975     FAETV,
      sphere_id                   sphere_id_3        ap  agg_prob
 3460   LFLCLYV   Leu-Phe-Leu-Cys-Leu-Tyr-Val  0.634517  0.999999)

In [63]:
neg_control_short_seqs_valid

,structure_id,structure_type,structure_id_3,ap,agg_prob,sequence_length
52,HASV,sphere,His-Ala-Ser-Val,0.501225,0.998187,4

In [64]:
# add these substitutes to the neg_control dataframe, replacing the short sequences
neg_control_final = neg_control.copy()

# drop from neg_control_final the short sequences
neg_control_final = neg_control_final[~((neg_control_final['sequence_length'] < 5))]

# add the substitutes
neg_control_ap_substitutes = neg_control_ap_substitutes.rename(columns={'sphere_id': 'structure_id', 'sphere_id_3': 'structure_id_3'})
neg_control_ap_substitutes = neg_control_ap_substitutes.assign(structure_type='sphere', ap=np.nan, agg_prob=np.nan, sequence_length=neg_control_ap_substitutes['structure_id'].apply(len))
neg_control_valid_substitutes = neg_control_valid_substitutes.rename(columns={'sphere_id': 'structure_id', 'sphere_id_3': 'structure_id_3'})
neg_control_valid_substitutes = neg_control_valid_substitutes.assign(structure_type='sphere', sequence_length=neg_control_valid_substitutes['structure_id'].apply(len))
neg_control_final = pd.concat([neg_control_final, neg_control_ap_substitutes, neg_control_valid_substitutes])
neg_control_final

,structure_id,structure_type,structure_id_3,ap,agg_prob,sequence_length
0,EFAHHYNQIL,fiber,NaN,NaN,NaN,10
1,VSVQPMECH,fiber,NaN,NaN,NaN,9
2,LYRPAPLEL,fiber,NaN,NaN,NaN,9
3,LQICQWAA,fiber,NaN,NaN,NaN,8
4,DAPFIMAY,fiber,NaN,NaN,NaN,8
5,LCPDSILVN,fiber,NaN,NaN,NaN,9
6,GPCIDQCSF,fiber,NaN,NaN,NaN,9
7,HALNGGTW,fiber,NaN,NaN,NaN,8
8,VYHEIDGFK,fiber,NaN,NaN,NaN,9
9,AWIRYDE,fiber,NaN,NaN,NaN,7
10,PEPFLNKTVM,fiber,NaN,NaN,NaN,10
11,EVLLAHAW,fiber,NaN,NaN,NaN,8
12,QVLGQWSLP,fiber,NaN,NaN,NaN,9
13,KTKEWHHE,fiber,NaN,NaN,NaN,8
14,KVLGDNPW,fiber,NaN,NaN,NaN,8
15,ERIRED,sphere,NaN,NaN,NaN,6
16,VCDVI,sphere,NaN,NaN,NaN,5
19,CEESFR,sphere,NaN,NaN,NaN,6
20,VEMASH,sphere,NaN,NaN,NaN,6
24,LFRQEE,sphere,NaN,NaN,NaN,6
28,VMAIVIE,sphere,NaN,NaN,NaN,7
29,RKEPIE,sphere,NaN,NaN,NaN,6
30,PNVVYQVWYT,fiber,Pro-Asn-Val-Val-Tyr-Gln-Val-Trp-Tyr-Thr,0.494724,0.999875,10
31,IFCLIRSYLM,fiber,Ile-Phe-Cys-Leu-Ile-Arg-Ser-Tyr-Leu-Met,0.510839,0.999926,10
32,RLSHNAMLY,fiber,Arg-Leu-Ser-His-Asn-Ala-Met-Leu-Tyr,0.441413,0.988917,9
33,WEFTGVNFT,fiber,Trp-Glu-Phe-Thr-Gly-Val-Asn-Phe-Thr,0.454921,0.992383,9
34,LEYGFYCV,fiber,Leu-Glu-Tyr-Gly-Phe-Tyr-Cys-Val,0.512835,0.999760,8
35,FVHIVNDQVV,fiber,Phe-Val-His-Ile-Val-Asn-Asp-Gln-Val-Val,0.437295,0.987502,10
36,PPFAQPMW,fiber,Pro-Pro-Phe-Ala-Gln-Pro-Met-Trp,0.511118,0.999560,8
37,LFLIACTPY,fiber,Leu-Phe-Leu-Ile-Ala-Cys-Thr-Pro-Tyr,0.541212,0.999937,9
38,WRWSDGCIL,fiber,Trp-Arg-Trp-Ser-Asp-Gly-Cys-Ile-Leu,0.486403,0.999381,9
39,VFESFTPY,fiber,Val-Phe-Glu-Ser-Phe-Thr-Pro-Tyr,0.563001,0.999969,8
40,TLAGIRWVTE,fiber,Thr-Leu-Ala-Gly-Ile-Arg-Trp-Val-Thr-Glu,0.431976,0.919771,10
41,PFVCLIVF,fiber,Pro-Phe-Val-Cys-Leu-Ile-Val-Phe,0.632314,0.999997,8
42,FIRSESFL,fiber,Phe-Ile-Arg-Ser-Glu-Ser-Phe-Leu,0.511274,0.998690,8
43,PVFVIVVFP,fiber,Pro-Val-Phe-Val-Ile-Val-Val-Phe-Pro,0.636027,0.999998,9
44,FPVSYAIY,fiber,Phe-Pro-Val-Ser-Tyr-Ala-Ile-Tyr,0.571085,0.999997,8
45,VIFDF,sphere,Val-Ile-Phe-Asp-Phe,0.579079,0.999942,5
46,WWVWE,sphere,Trp-Trp-Val-Trp-Glu,0.514255,0.999820,5
47,WFFWFW,sphere,Trp-Phe-Phe-Trp-Phe-Trp,0.575281,0.999999,6
48,CFMVAVF,sphere,Cys-Phe-Met-Val-Ala-Val-Phe,0.602417,0.999971,7
49,WAVFGVD,sphere,Trp-Ala-Val-Phe-Gly-Val-Asp,0.514721,0.999238,7
50,FYFIL,sphere,Phe-Tyr-Phe-Ile-Leu,0.643787,0.999999,5
51,WAIEF,sphere,Trp-Ala-Ile-Glu-Phe,0.557108,0.999842,5
53,CHGLICA,sphere,Cys-His-Gly-Leu-Ile-Cys-Ala,0.444924,0.976472,7
54,LFVILP,sphere,Leu-Phe-Val-Ile-Leu-Pro,0.643863,0.999979,6
55,FACWV,sphere,Phe-Ala-Cys-Trp-Val,0.663913,0.999999,5
56,CMLWM,sphere,Cys-Met-Leu-Trp-Met,0.604330,0.999941,5
57,VLWYIWI,sphere,Val-Leu-Trp-Tyr-Ile-Trp-Ile,0.602887,0.999999,7
58,WMAHA,sphere,Trp-Met-Ala-His-Ala,0.500076,0.999284,5
59,LVIEFF,sphere,Leu-Val-Ile-Glu-Phe-Phe,0.586371,0.999942,6
3632,REMNSFE,sphere,NaN,NaN,NaN,7
1485,VEFAV,sphere,NaN,NaN,NaN,5
3885,MIVDCVL,sphere,NaN,NaN,NaN,7
3876,PLVEILG,sphere,NaN,NaN,NaN,7
2323,ERWDK,sphere,NaN,NaN,NaN,5
2617,QWHECK,sphere,NaN,NaN,NaN,6
3561,IRDYKE,sphere,NaN,NaN,NaN,6
1975,FAETV,sphere,NaN,NaN,NaN,5
3460,LFLCLYV,sphere,Leu-Phe-Leu-Cys-Leu-Tyr-Val,0.634517,0.999999,7

In [65]:
# check per length of structure_id
neg_control_final['structure_length'] = neg_control_final['structure_id'].apply(len)

# do a count per structure_type and structure_length
neg_control_counts = neg_control_final.groupby(['structure_length']).size().reset_index(name='count')
neg_control_counts

   structure_length  count
0                 5     11
1                 6     10
2                 7     10
3                 8     12
4                 9     11
5                10      6

In [66]:
all_lengths = range(5, 11)
ALPHABET = 'ACDEFGHIKLMNPQRSTVWY'
np.random.seed(42)
current_count = 12

def generate_random_peptide(length):
    return ''.join(np.random.choice(list(ALPHABET), size=length))

new_peptides = []
while current_count < 15:
    length = np.random.choice(all_lengths)
    random_peptide_1= generate_random_peptide(length)
    neg_control_final = pd.concat([neg_control_final, pd.DataFrame({
        'structure_id': [random_peptide_1],
        'structure_id_3': [None],
        'structure_type': ['random'],
        'structure_length': [length]
    })], ignore_index=True)
    current_count += 1
    new_peptides.append(random_peptide_1)

neg_control_final.reset_index(drop=True, inplace=True)
neg_control_final

,structure_id,structure_type,structure_id_3,ap,agg_prob,sequence_length,structure_length
0,EFAHHYNQIL,fiber,NaN,NaN,NaN,10.0,10
1,VSVQPMECH,fiber,NaN,NaN,NaN,9.0,9
2,LYRPAPLEL,fiber,NaN,NaN,NaN,9.0,9
3,LQICQWAA,fiber,NaN,NaN,NaN,8.0,8
4,DAPFIMAY,fiber,NaN,NaN,NaN,8.0,8
...,...,...,...,...,...,...,...
58,FAETV,sphere,NaN,NaN,NaN,5.0,5
59,LFLCLYV,sphere,Leu-Phe-Leu-Cys-Leu-Tyr-Val,0.634517,0.999999,7.0,7
60,RMIHWMME,random,None,NaN,NaN,NaN,8
61,CNGCANN,random,None,NaN,NaN,NaN,7
62,TLSRR,random,None,NaN,NaN,NaN,5

In [68]:
# save to csv
neg_control_final.to_csv('negative_control_structures_new.csv', index=False)

# save peptides as a fasta file
with open('negative_control_structures_new.fasta', 'w') as fasta_file:
    for idx, row in neg_control_final.iterrows():
        fasta_file.write(f">{row['structure_type']}_{idx}\n")
        fasta_file.write(f"{row['structure_id']}\n")