In [1]:
import pandas as pd
import numpy as np

# load negative control structures
neg_ctrl_df = pd.read_csv('negative_control_structures.csv')
neg_ctrl_df

,structure_id,structure_type,structure_id_3,ap,agg_prob,structure_length
0,EFAHHYNQIL,fiber,NaN,NaN,NaN,10
1,VSVQPMECH,fiber,NaN,NaN,NaN,9
2,LYRPAPLEL,fiber,NaN,NaN,NaN,9
3,LQICQWAA,fiber,NaN,NaN,NaN,8
4,DAPFIMAY,fiber,NaN,NaN,NaN,8
5,ERIRED,sphere,NaN,NaN,NaN,6
6,VCDVI,sphere,NaN,NaN,NaN,5
7,ELVM,sphere,NaN,NaN,NaN,4
8,PEHR,sphere,NaN,NaN,NaN,4
9,CEESFR,sphere,NaN,NaN,NaN,6
10,PNVVYQVWYT,fiber,Pro-Asn-Val-Val-Tyr-Gln-Val-Trp-Tyr-Thr,0.494724,0.999875,10
11,IFCLIRSYLM,fiber,Ile-Phe-Cys-Leu-Ile-Arg-Ser-Tyr-Leu-Met,0.510839,0.999926,10
12,RLSHNAMLY,fiber,Arg-Leu-Ser-His-Asn-Ala-Met-Leu-Tyr,0.441413,0.988917,9
13,WEFTGVNFT,fiber,Trp-Glu-Phe-Thr-Gly-Val-Asn-Phe-Thr,0.454921,0.992383,9
14,LEYGFYCV,fiber,Leu-Glu-Tyr-Gly-Phe-Tyr-Cys-Val,0.512835,0.999760,8
15,VIFDF,sphere,Val-Ile-Phe-Asp-Phe,0.579079,0.999942,5
16,WWVWE,sphere,Trp-Trp-Val-Trp-Glu,0.514255,0.999820,5
17,WFFWFW,sphere,Trp-Phe-Phe-Trp-Phe-Trp,0.575281,0.999999,6
18,CFMVAVF,sphere,Cys-Phe-Met-Val-Ala-Val-Phe,0.602417,0.999971,7
19,WAVFGVD,sphere,Trp-Ala-Val-Phe-Gly-Val-Asp,0.514721,0.999238,7
20,WRTD,random,NaN,NaN,NaN,4
21,ISLC,random,NaN,NaN,NaN,4
22,PWPD,random,NaN,NaN,NaN,4
23,DGTPM,random,NaN,NaN,NaN,5
24,VKFYA,random,NaN,NaN,NaN,5
25,KKYFYL,random,NaN,NaN,NaN,6
26,HPKQAH,random,NaN,NaN,NaN,6
27,TAWEQQY,random,NaN,NaN,NaN,7
28,NVIIKGG,random,NaN,NaN,NaN,7
29,WWLYIWN,random,NaN,NaN,NaN,7
30,IERTAFKV,random,NaN,NaN,NaN,8
31,YMRDIATQ,random,NaN,NaN,NaN,8
32,IQDMVQVDH,random,NaN,NaN,NaN,9
33,IFAQYSDWNI,random,NaN,NaN,NaN,10
34,ECPFGIGIEF,random,NaN,NaN,NaN,10

In [2]:
# rename column 'structure_id' to 'peptide'
neg_ctrl_df = neg_ctrl_df.rename(columns={'structure_id': 'peptide'})

In [3]:
# load rmoi_and_ap_summary_total
rmoi_ap_summary_df = pd.read_csv('rmoi_and_ap_summary_total.csv')
rmoi_ap_summary_df

,morphology,peptide,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
0,fibers,CVSAPGIFHC,0.376627,0.070951,1.959020,0.058305,3,3,0.295179,0.409692,0.425011,2.022145,1.947726,1.907187
1,fibers,FTFIPGWVDL,0.398661,0.096232,2.439498,0.078677,3,3,0.307051,0.390002,0.498930,2.478425,2.491124,2.348946
2,fibers,HYVSGRFLIY,0.495999,0.025635,2.212450,0.053054,3,3,0.520591,0.497972,0.469435,2.176169,2.187840,2.273340
3,fibers,ILSCPGWPFY,0.453337,0.339622,2.715835,0.164816,3,3,0.240490,0.845007,0.274513,2.817635,2.525681,2.804190
4,fibers,ILSFPDKVTY,0.398988,0.089944,2.194466,0.054625,3,3,0.458935,0.442462,0.295566,2.134727,2.241865,2.206807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,unsupervised,MKFYF,0.340749,0.053622,2.140956,0.032481,3,3,0.340139,0.394673,0.287434,2.104693,2.150798,2.167378
75,unsupervised,PQVPCMGDL,0.436468,0.051255,1.349231,0.017448,3,3,0.377295,0.465066,0.467043,1.329804,1.354323,1.363567
76,unsupervised,WVWLCQG,0.367673,0.120846,2.380745,0.053993,3,3,0.338767,0.263900,0.500350,2.426710,2.394241,2.321285
77,unsupervised,YPDYSM,0.419641,0.279942,2.004831,0.033479,3,3,0.737875,0.211401,0.309647,2.035946,2.009141,1.969406
78,unsupervised,YYCDVERMIC,0.374314,0.115319,1.878686,0.043352,3,3,0.307397,0.507472,0.308073,1.917980,1.832180,1.885899

In [4]:
# left join on neg_ctrl_df and rmoi_ap_summary_df on 'structure_id' and 'peptide'
merged_df = pd.merge(neg_ctrl_df, rmoi_ap_summary_df, on=['peptide'], how='left')
merged_df

,peptide,structure_type,structure_id_3,ap,agg_prob,structure_length,morphology,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
0,EFAHHYNQIL,fiber,NaN,NaN,NaN,10,neg_morph,0.563333,0.084213,1.438246,0.031033,3,3,0.660130,0.506904,0.522966,1.413070,1.428751,1.472918
1,VSVQPMECH,fiber,NaN,NaN,NaN,9,neg_morph,0.442553,0.046878,1.377653,0.006778,3,3,0.407730,0.424076,0.495854,1.385169,1.372005,1.375784
2,LYRPAPLEL,fiber,NaN,NaN,NaN,9,neg_morph,0.343279,0.049025,1.716276,0.017749,3,3,0.328363,0.303444,0.398030,1.725839,1.727192,1.695796
3,LQICQWAA,fiber,NaN,NaN,NaN,8,neg_morph,0.481083,0.083499,1.831733,0.053068,3,3,0.472290,0.402329,0.568631,1.835404,1.776925,1.882870
4,DAPFIMAY,fiber,NaN,NaN,NaN,8,neg_morph,0.612673,0.078738,1.655658,0.027332,3,3,0.632853,0.525810,0.679358,1.643816,1.636244,1.686914
5,ERIRED,sphere,NaN,NaN,NaN,6,neg_morph,0.781964,0.047416,1.107696,0.005130,3,3,0.769607,0.834335,0.741950,1.111235,1.110042,1.101813
6,VCDVI,sphere,NaN,NaN,NaN,5,neg_morph,0.802133,0.045522,1.060584,0.000371,3,3,0.837241,0.818458,0.750699,1.060793,1.060156,1.060805
7,ELVM,sphere,NaN,NaN,NaN,4,neg_morph,0.437623,0.084286,1.031153,0.001514,3,3,0.478109,0.494026,0.340733,1.032637,1.029612,1.031210
8,PEHR,sphere,NaN,NaN,NaN,4,neg_morph,0.697356,0.114706,1.051392,0.004688,3,3,0.659819,0.606121,0.826127,1.056559,1.047411,1.050205
9,CEESFR,sphere,NaN,NaN,NaN,6,neg_morph,0.833369,0.033420,1.104380,0.019890,3,3,0.796793,0.862311,0.841003,1.082543,1.109137,1.121459
10,PNVVYQVWYT,fiber,Pro-Asn-Val-Val-Tyr-Gln-Val-Trp-Tyr-Thr,0.494724,0.999875,10,neg_morph,0.388180,0.081184,2.506343,0.037630,3,3,0.334895,0.481616,0.348029,2.549334,2.479385,2.490310
11,IFCLIRSYLM,fiber,Ile-Phe-Cys-Leu-Ile-Arg-Ser-Tyr-Leu-Met,0.510839,0.999926,10,neg_morph,0.442832,0.110259,1.943411,0.030072,3,3,0.315520,0.507449,0.505526,1.965083,1.956072,1.909079
12,RLSHNAMLY,fiber,Arg-Leu-Ser-His-Asn-Ala-Met-Leu-Tyr,0.441413,0.988917,9,neg_morph,0.332462,0.014049,1.722893,0.037711,3,3,0.336337,0.344167,0.316883,1.697040,1.705475,1.766166
13,WEFTGVNFT,fiber,Trp-Glu-Phe-Thr-Gly-Val-Asn-Phe-Thr,0.454921,0.992383,9,neg_morph,0.539255,0.097904,2.208991,0.020505,3,3,0.648432,0.510069,0.459263,2.230452,2.189599,2.206922
14,LEYGFYCV,fiber,Leu-Glu-Tyr-Gly-Phe-Tyr-Cys-Val,0.512835,0.999760,8,neg_morph,0.463419,0.155541,2.170786,0.010177,3,3,0.637675,0.338623,0.413958,2.174837,2.159206,2.178313
15,VIFDF,sphere,Val-Ile-Phe-Asp-Phe,0.579079,0.999942,5,neg_morph,0.528324,0.124981,1.834714,0.008264,3,3,0.672120,0.467025,0.445827,1.843829,1.832599,1.827713
16,WWVWE,sphere,Trp-Trp-Val-Trp-Glu,0.514255,0.999820,5,neg_morph,0.379367,0.083541,2.769770,0.020897,3,3,0.366098,0.303254,0.468748,2.783618,2.745732,2.779959
17,WFFWFW,sphere,Trp-Phe-Phe-Trp-Phe-Trp,0.575281,0.999999,6,neg_morph,0.641295,0.349341,3.970156,0.038951,3,3,0.238996,0.868053,0.816837,3.925246,3.994720,3.990504
18,CFMVAVF,sphere,Cys-Phe-Met-Val-Ala-Val-Phe,0.602417,0.999971,7,neg_morph,0.878688,0.011373,2.985407,0.042653,3,3,0.871235,0.891779,0.873051,2.936173,3.008888,3.011160
19,WAVFGVD,sphere,Trp-Ala-Val-Phe-Gly-Val-Asp,0.514721,0.999238,7,neg_morph,0.389549,0.153028,2.489687,0.069016,3,3,0.229995,0.403566,0.535087,2.519295,2.410806,2.538959
20,WRTD,random,NaN,NaN,NaN,4,neg_morph,0.359819,0.042289,2.167509,0.026649,3,3,0.311878,0.391827,0.375752,2.166477,2.141391,2.194659
21,ISLC,random,NaN,NaN,NaN,4,neg_morph,0.320608,0.080915,1.028010,0.004027,3,3,0.411264,0.294857,0.255701,1.032642,1.026045,1.025342
22,PWPD,random,NaN,NaN,NaN,4,neg_morph,0.486471,0.076422,1.758025,0.035479,3,3,0.510374,0.548084,0.400954,1.796072,1.725845,1.752159
23,DGTPM,random,NaN,NaN,NaN,5,neg_morph,0.489734,0.064494,1.021562,0.005415,3,3,0.415401,0.530840,0.522960,1.017867,1.019041,1.027778
24,VKFYA,random,NaN,NaN,NaN,5,neg_morph,0.408917,0.089500,1.816246,0.030985,3,3,0.393457,0.505141,0.328155,1.782407,1.823103,1.843228
25,KKYFYL,random,NaN,NaN,NaN,6,neg_morph,0.589000,0.135064,1.614019,0.019136,3,3,0.490315,0.742929,0.533756,1.612142,1.595891,1.634024
26,HPKQAH,random,NaN,NaN,NaN,6,neg_morph,0.757235,0.071035,1.119905,0.011323,3,3,0.717629,0.714833,0.839244,1.125914,1.106844,1.126957
27,TAWEQQY,random,NaN,NaN,NaN,7,neg_morph,0.544922,0.058648,1.796597,0.011614,3,3,0.591685,0.479120,0.563960,1.787867,1.809778,1.792147
28,NVIIKGG,random,NaN,NaN,NaN,7,neg_morph,0.817114,0.034819,1.050209,0.002682,3,3,0.811742,0.785294,0.854307,1.047471,1.052832,1.050326
29,WWLYIWN,random,NaN,NaN,NaN,7,neg_morph,0.507293,0.068873,2.868627,0.101548,3,3,0.464792,0.470331,0.586756,2.917796,2.936231,2.751854
30,IERTAFKV,random,NaN,NaN,NaN,8,neg_morph,0.625765,0.053083,1.400898,0.022470,3,3,0.628613,0.571315,0.677366,1.389518,1.426781,1.386395
31,YMRDIATQ,random,NaN,NaN,NaN,8,neg_morph,0.360984,0.030441,1.586861,0.017878,3,3,0.369222,0.386457,0.327272,1.567334,1.590827,1.602423
32,IQDMVQVDH,random,NaN,NaN,NaN,9,neg_morph,0.724905,0.155265,1.134272,0.009706,3,3,0.854196,0.552695,0.767822,1.124615,1.144027,1.134173
33,IFAQYSDWNI,random,NaN,NaN,NaN,10,neg_morph,0.507001,0.093214,2.283274,0.042482,3,3,0.614490,0.458108,0.448406,2.237008,2.320528,2.292284
34,ECPFGIGIEF,random,NaN,NaN,NaN,10,neg_morph,0.684839,0.135674,1.868426,0.017269,3,3,0.728895,0.793010,0.532612,1.856597,1.860437,1.888242

In [5]:
# get df with random peptides, where structure_type is 'random'
random_peptides_df = merged_df[merged_df['structure_type'] == 'random']
random_peptides_df

,peptide,structure_type,structure_id_3,ap,agg_prob,structure_length,morphology,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
20,WRTD,random,NaN,NaN,NaN,4,neg_morph,0.359819,0.042289,2.167509,0.026649,3,3,0.311878,0.391827,0.375752,2.166477,2.141391,2.194659
21,ISLC,random,NaN,NaN,NaN,4,neg_morph,0.320608,0.080915,1.028010,0.004027,3,3,0.411264,0.294857,0.255701,1.032642,1.026045,1.025342
22,PWPD,random,NaN,NaN,NaN,4,neg_morph,0.486471,0.076422,1.758025,0.035479,3,3,0.510374,0.548084,0.400954,1.796072,1.725845,1.752159
23,DGTPM,random,NaN,NaN,NaN,5,neg_morph,0.489734,0.064494,1.021562,0.005415,3,3,0.415401,0.530840,0.522960,1.017867,1.019041,1.027778
24,VKFYA,random,NaN,NaN,NaN,5,neg_morph,0.408917,0.089500,1.816246,0.030985,3,3,0.393457,0.505141,0.328155,1.782407,1.823103,1.843228
25,KKYFYL,random,NaN,NaN,NaN,6,neg_morph,0.589000,0.135064,1.614019,0.019136,3,3,0.490315,0.742929,0.533756,1.612142,1.595891,1.634024
26,HPKQAH,random,NaN,NaN,NaN,6,neg_morph,0.757235,0.071035,1.119905,0.011323,3,3,0.717629,0.714833,0.839244,1.125914,1.106844,1.126957
27,TAWEQQY,random,NaN,NaN,NaN,7,neg_morph,0.544922,0.058648,1.796597,0.011614,3,3,0.591685,0.479120,0.563960,1.787867,1.809778,1.792147
28,NVIIKGG,random,NaN,NaN,NaN,7,neg_morph,0.817114,0.034819,1.050209,0.002682,3,3,0.811742,0.785294,0.854307,1.047471,1.052832,1.050326
29,WWLYIWN,random,NaN,NaN,NaN,7,neg_morph,0.507293,0.068873,2.868627,0.101548,3,3,0.464792,0.470331,0.586756,2.917796,2.936231,2.751854
30,IERTAFKV,random,NaN,NaN,NaN,8,neg_morph,0.625765,0.053083,1.400898,0.022470,3,3,0.628613,0.571315,0.677366,1.389518,1.426781,1.386395
31,YMRDIATQ,random,NaN,NaN,NaN,8,neg_morph,0.360984,0.030441,1.586861,0.017878,3,3,0.369222,0.386457,0.327272,1.567334,1.590827,1.602423
32,IQDMVQVDH,random,NaN,NaN,NaN,9,neg_morph,0.724905,0.155265,1.134272,0.009706,3,3,0.854196,0.552695,0.767822,1.124615,1.144027,1.134173
33,IFAQYSDWNI,random,NaN,NaN,NaN,10,neg_morph,0.507001,0.093214,2.283274,0.042482,3,3,0.614490,0.458108,0.448406,2.237008,2.320528,2.292284
34,ECPFGIGIEF,random,NaN,NaN,NaN,10,neg_morph,0.684839,0.135674,1.868426,0.017269,3,3,0.728895,0.793010,0.532612,1.856597,1.860437,1.888242

In [6]:
# check how many have aggregation_propensity_mean > 1.8
high_ap_random_df = random_peptides_df[random_peptides_df['aggregation_propensity_mean'] > 1.8]
high_ap_random_df

,peptide,structure_type,structure_id_3,ap,agg_prob,structure_length,morphology,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
20,WRTD,random,NaN,NaN,NaN,4,neg_morph,0.359819,0.042289,2.167509,0.026649,3,3,0.311878,0.391827,0.375752,2.166477,2.141391,2.194659
24,VKFYA,random,NaN,NaN,NaN,5,neg_morph,0.408917,0.089500,1.816246,0.030985,3,3,0.393457,0.505141,0.328155,1.782407,1.823103,1.843228
29,WWLYIWN,random,NaN,NaN,NaN,7,neg_morph,0.507293,0.068873,2.868627,0.101548,3,3,0.464792,0.470331,0.586756,2.917796,2.936231,2.751854
33,IFAQYSDWNI,random,NaN,NaN,NaN,10,neg_morph,0.507001,0.093214,2.283274,0.042482,3,3,0.614490,0.458108,0.448406,2.237008,2.320528,2.292284
34,ECPFGIGIEF,random,NaN,NaN,NaN,10,neg_morph,0.684839,0.135674,1.868426,0.017269,3,3,0.728895,0.793010,0.532612,1.856597,1.860437,1.888242

In [7]:
# get df with sphere and fiber structure_type, which have ap as NaN
sphere_fiber_pre_ap_df = merged_df[(merged_df['structure_type'].isin(['sphere', 'fiber'])) & (merged_df['ap'].isna())]
sphere_fiber_pre_ap_df

,peptide,structure_type,structure_id_3,ap,agg_prob,structure_length,morphology,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
0,EFAHHYNQIL,fiber,NaN,NaN,NaN,10,neg_morph,0.563333,0.084213,1.438246,0.031033,3,3,0.660130,0.506904,0.522966,1.413070,1.428751,1.472918
1,VSVQPMECH,fiber,NaN,NaN,NaN,9,neg_morph,0.442553,0.046878,1.377653,0.006778,3,3,0.407730,0.424076,0.495854,1.385169,1.372005,1.375784
2,LYRPAPLEL,fiber,NaN,NaN,NaN,9,neg_morph,0.343279,0.049025,1.716276,0.017749,3,3,0.328363,0.303444,0.398030,1.725839,1.727192,1.695796
3,LQICQWAA,fiber,NaN,NaN,NaN,8,neg_morph,0.481083,0.083499,1.831733,0.053068,3,3,0.472290,0.402329,0.568631,1.835404,1.776925,1.882870
4,DAPFIMAY,fiber,NaN,NaN,NaN,8,neg_morph,0.612673,0.078738,1.655658,0.027332,3,3,0.632853,0.525810,0.679358,1.643816,1.636244,1.686914
5,ERIRED,sphere,NaN,NaN,NaN,6,neg_morph,0.781964,0.047416,1.107696,0.005130,3,3,0.769607,0.834335,0.741950,1.111235,1.110042,1.101813
6,VCDVI,sphere,NaN,NaN,NaN,5,neg_morph,0.802133,0.045522,1.060584,0.000371,3,3,0.837241,0.818458,0.750699,1.060793,1.060156,1.060805
7,ELVM,sphere,NaN,NaN,NaN,4,neg_morph,0.437623,0.084286,1.031153,0.001514,3,3,0.478109,0.494026,0.340733,1.032637,1.029612,1.031210
8,PEHR,sphere,NaN,NaN,NaN,4,neg_morph,0.697356,0.114706,1.051392,0.004688,3,3,0.659819,0.606121,0.826127,1.056559,1.047411,1.050205
9,CEESFR,sphere,NaN,NaN,NaN,6,neg_morph,0.833369,0.033420,1.104380,0.019890,3,3,0.796793,0.862311,0.841003,1.082543,1.109137,1.121459

In [ ]:
# check how many have > 1.8
high_rmoi_sphere_fiber_df = sphere_fiber_pre_ap_df[sphere_fiber_pre_ap_df['aggregation_propensity_mean'] > 1.8]
high_rmoi_sphere_fiber_df

,peptide,structure_type,structure_id_3,ap,agg_prob,structure_length,morphology,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
3,LQICQWAA,fiber,NaN,NaN,NaN,8,neg_morph,0.481083,0.083499,1.831733,0.053068,3,3,0.47229,0.402329,0.568631,1.835404,1.776925,1.88287

In [9]:
# get df with sphere and fiber structure_type, which have ap as not NaN
sphere_fiber_post_ap_df = merged_df[(merged_df['structure_type'].isin(['sphere', 'fiber'])) & (~merged_df['ap'].isna())]
sphere_fiber_post_ap_df

,peptide,structure_type,structure_id_3,ap,agg_prob,structure_length,morphology,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
10,PNVVYQVWYT,fiber,Pro-Asn-Val-Val-Tyr-Gln-Val-Trp-Tyr-Thr,0.494724,0.999875,10,neg_morph,0.388180,0.081184,2.506343,0.037630,3,3,0.334895,0.481616,0.348029,2.549334,2.479385,2.490310
11,IFCLIRSYLM,fiber,Ile-Phe-Cys-Leu-Ile-Arg-Ser-Tyr-Leu-Met,0.510839,0.999926,10,neg_morph,0.442832,0.110259,1.943411,0.030072,3,3,0.315520,0.507449,0.505526,1.965083,1.956072,1.909079
12,RLSHNAMLY,fiber,Arg-Leu-Ser-His-Asn-Ala-Met-Leu-Tyr,0.441413,0.988917,9,neg_morph,0.332462,0.014049,1.722893,0.037711,3,3,0.336337,0.344167,0.316883,1.697040,1.705475,1.766166
13,WEFTGVNFT,fiber,Trp-Glu-Phe-Thr-Gly-Val-Asn-Phe-Thr,0.454921,0.992383,9,neg_morph,0.539255,0.097904,2.208991,0.020505,3,3,0.648432,0.510069,0.459263,2.230452,2.189599,2.206922
14,LEYGFYCV,fiber,Leu-Glu-Tyr-Gly-Phe-Tyr-Cys-Val,0.512835,0.999760,8,neg_morph,0.463419,0.155541,2.170786,0.010177,3,3,0.637675,0.338623,0.413958,2.174837,2.159206,2.178313
15,VIFDF,sphere,Val-Ile-Phe-Asp-Phe,0.579079,0.999942,5,neg_morph,0.528324,0.124981,1.834714,0.008264,3,3,0.672120,0.467025,0.445827,1.843829,1.832599,1.827713
16,WWVWE,sphere,Trp-Trp-Val-Trp-Glu,0.514255,0.999820,5,neg_morph,0.379367,0.083541,2.769770,0.020897,3,3,0.366098,0.303254,0.468748,2.783618,2.745732,2.779959
17,WFFWFW,sphere,Trp-Phe-Phe-Trp-Phe-Trp,0.575281,0.999999,6,neg_morph,0.641295,0.349341,3.970156,0.038951,3,3,0.238996,0.868053,0.816837,3.925246,3.994720,3.990504
18,CFMVAVF,sphere,Cys-Phe-Met-Val-Ala-Val-Phe,0.602417,0.999971,7,neg_morph,0.878688,0.011373,2.985407,0.042653,3,3,0.871235,0.891779,0.873051,2.936173,3.008888,3.011160
19,WAVFGVD,sphere,Trp-Ala-Val-Phe-Gly-Val-Asp,0.514721,0.999238,7,neg_morph,0.389549,0.153028,2.489687,0.069016,3,3,0.229995,0.403566,0.535087,2.519295,2.410806,2.538959

In [10]:
# check how many have ap > 1.8
high_ap_sphere_fiber_df = sphere_fiber_post_ap_df[sphere_fiber_post_ap_df['aggregation_propensity_mean'] > 1.8]
high_ap_sphere_fiber_df

,peptide,structure_type,structure_id_3,ap,agg_prob,structure_length,morphology,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
10,PNVVYQVWYT,fiber,Pro-Asn-Val-Val-Tyr-Gln-Val-Trp-Tyr-Thr,0.494724,0.999875,10,neg_morph,0.388180,0.081184,2.506343,0.037630,3,3,0.334895,0.481616,0.348029,2.549334,2.479385,2.490310
11,IFCLIRSYLM,fiber,Ile-Phe-Cys-Leu-Ile-Arg-Ser-Tyr-Leu-Met,0.510839,0.999926,10,neg_morph,0.442832,0.110259,1.943411,0.030072,3,3,0.315520,0.507449,0.505526,1.965083,1.956072,1.909079
13,WEFTGVNFT,fiber,Trp-Glu-Phe-Thr-Gly-Val-Asn-Phe-Thr,0.454921,0.992383,9,neg_morph,0.539255,0.097904,2.208991,0.020505,3,3,0.648432,0.510069,0.459263,2.230452,2.189599,2.206922
14,LEYGFYCV,fiber,Leu-Glu-Tyr-Gly-Phe-Tyr-Cys-Val,0.512835,0.999760,8,neg_morph,0.463419,0.155541,2.170786,0.010177,3,3,0.637675,0.338623,0.413958,2.174837,2.159206,2.178313
15,VIFDF,sphere,Val-Ile-Phe-Asp-Phe,0.579079,0.999942,5,neg_morph,0.528324,0.124981,1.834714,0.008264,3,3,0.672120,0.467025,0.445827,1.843829,1.832599,1.827713
16,WWVWE,sphere,Trp-Trp-Val-Trp-Glu,0.514255,0.999820,5,neg_morph,0.379367,0.083541,2.769770,0.020897,3,3,0.366098,0.303254,0.468748,2.783618,2.745732,2.779959
17,WFFWFW,sphere,Trp-Phe-Phe-Trp-Phe-Trp,0.575281,0.999999,6,neg_morph,0.641295,0.349341,3.970156,0.038951,3,3,0.238996,0.868053,0.816837,3.925246,3.994720,3.990504
18,CFMVAVF,sphere,Cys-Phe-Met-Val-Ala-Val-Phe,0.602417,0.999971,7,neg_morph,0.878688,0.011373,2.985407,0.042653,3,3,0.871235,0.891779,0.873051,2.936173,3.008888,3.011160
19,WAVFGVD,sphere,Trp-Ala-Val-Phe-Gly-Val-Asp,0.514721,0.999238,7,neg_morph,0.389549,0.153028,2.489687,0.069016,3,3,0.229995,0.403566,0.535087,2.519295,2.410806,2.538959

In [15]:
# get df with unsupervised type
unsupervised_df = rmoi_ap_summary_df[rmoi_ap_summary_df['morphology'] == 'unsupervised']
unsupervised_df

,morphology,peptide,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
65,unsupervised,CFLI,0.536282,0.149403,1.591032,0.031082,3,3,0.371173,0.662145,0.575528,1.626830,1.575358,1.570909
66,unsupervised,CIKYEHT,0.568490,0.075989,1.820543,0.019709,3,3,0.631853,0.484243,0.589373,1.842257,1.803784,1.815589
67,unsupervised,CYVIMIVLRK,0.704004,0.080684,1.290151,0.024463,3,3,0.749498,0.610846,0.751667,1.262078,1.301472,1.306902
68,unsupervised,EWKNE,0.574010,0.099007,1.573135,0.011585,3,3,0.685785,0.497331,0.538913,1.560122,1.582324,1.576961
69,unsupervised,FCIICHDPD,0.372138,0.048744,1.661720,0.002951,3,3,0.351677,0.336960,0.427777,1.664795,1.658910,1.661456
70,unsupervised,GLPCCNRS,0.805560,0.070769,1.153883,0.012585,3,3,0.725068,0.858015,0.833596,1.142006,1.167073,1.152570
71,unsupervised,ICVT,0.413978,0.143967,1.053034,0.010129,3,3,0.267210,0.419753,0.554970,1.042030,1.055104,1.061969
72,unsupervised,ILFWYP,0.855180,0.019672,3.093685,0.087354,3,3,0.839153,0.877134,0.849253,3.005708,3.094945,3.180402
73,unsupervised,MADRKTWY,0.470531,0.151662,1.909269,0.025737,3,3,0.632692,0.446714,0.332187,1.893977,1.894847,1.938984
74,unsupervised,MKFYF,0.340749,0.053622,2.140956,0.032481,3,3,0.340139,0.394673,0.287434,2.104693,2.150798,2.167378
75,unsupervised,PQVPCMGDL,0.436468,0.051255,1.349231,0.017448,3,3,0.377295,0.465066,0.467043,1.329804,1.354323,1.363567
76,unsupervised,WVWLCQG,0.367673,0.120846,2.380745,0.053993,3,3,0.338767,0.263900,0.500350,2.426710,2.394241,2.321285
77,unsupervised,YPDYSM,0.419641,0.279942,2.004831,0.033479,3,3,0.737875,0.211401,0.309647,2.035946,2.009141,1.969406
78,unsupervised,YYCDVERMIC,0.374314,0.115319,1.878686,0.043352,3,3,0.307397,0.507472,0.308073,1.917980,1.832180,1.885899

In [16]:
# check how many have aggregation_propensity_mean > 1.8
high_ap_unsupervised_df = unsupervised_df[unsupervised_df['aggregation_propensity_mean'] > 1.8]
high_ap_unsupervised_df

,morphology,peptide,RMOI_mean,RMOI_std,aggregation_propensity_mean,aggregation_propensity_std,n_runs_RMOI,n_runs_AP,RMOI_run_1,RMOI_run_2,RMOI_run_3,aggregation_propensity_run_1,aggregation_propensity_run_2,aggregation_propensity_run_3
66,unsupervised,CIKYEHT,0.568490,0.075989,1.820543,0.019709,3,3,0.631853,0.484243,0.589373,1.842257,1.803784,1.815589
72,unsupervised,ILFWYP,0.855180,0.019672,3.093685,0.087354,3,3,0.839153,0.877134,0.849253,3.005708,3.094945,3.180402
73,unsupervised,MADRKTWY,0.470531,0.151662,1.909269,0.025737,3,3,0.632692,0.446714,0.332187,1.893977,1.894847,1.938984
74,unsupervised,MKFYF,0.340749,0.053622,2.140956,0.032481,3,3,0.340139,0.394673,0.287434,2.104693,2.150798,2.167378
76,unsupervised,WVWLCQG,0.367673,0.120846,2.380745,0.053993,3,3,0.338767,0.263900,0.500350,2.426710,2.394241,2.321285
77,unsupervised,YPDYSM,0.419641,0.279942,2.004831,0.033479,3,3,0.737875,0.211401,0.309647,2.035946,2.009141,1.969406
78,unsupervised,YYCDVERMIC,0.374314,0.115319,1.878686,0.043352,3,3,0.307397,0.507472,0.308073,1.917980,1.832180,1.885899