In [36]:
import json
import pandas as pd
import matplotlib.pyplot as plt

In [37]:
sphere_sample ={
    'hydrophobic_moment': [0.6, 1.00],
    'net_charge': [0.4, 0.6],
}

fiber_sample = {
    'has_beta_sheet_content': [0.1, 1],
    'net_charge': [0.4, 0.6],
}

samples = [sphere_sample, fiber_sample]

In [38]:
# read txt file with list of peptides
with open('gen_peptides/generated_random_init.txt', 'r') as f:
    peptides = [line.strip() for line in f.readlines()]

len(set(peptides))

4800

In [39]:
min_max = {
    "has_beta_sheet_content": (0.0, 1.0),
    "hydrophobic_moment": (0.000000, 1.998000),
    "net_charge": (-6.000000, 6.000000),
    "ap":(0.959986, 2.897030)
}

for sample in samples:
    for key in sample:
        if key in ['length','sequence']:
            continue
        sample[key][0] = sample[key][0] * (min_max[key][1] - min_max[key][0]) + min_max[key][0]
        sample[key][1] = sample[key][1] * (min_max[key][1] - min_max[key][0]) + min_max[key][0]

samples

[{'hydrophobic_moment': [1.1987999999999999, 1.998],
  'net_charge': [-1.1999999999999993, 1.1999999999999993]},
 {'has_beta_sheet_content': [0.1, 1.0],
  'net_charge': [-1.1999999999999993, 1.1999999999999993]}]

In [23]:
fiber_samples = pd.read_csv('gen_peptides/random_metrics.csv')
fiber_samples['has_beta_sheet_content'] = (fiber_samples['beta_sheet_fraction'] > 0.1).astype(int)
fiber_samples.drop(columns=['peptide_id'], inplace=True)
fiber_samples.drop_duplicates(subset=['sequence'], inplace=True)
fiber_samples

,sequence,beta_sheet_fraction,hydrophobic_moment,net_charge,has_beta_sheet_content
0,TAFFHSVG,0.0,0.491250,0,0
1,VYSGTKWVFG,0.0,0.365000,1,0
2,WGCQSH,0.0,0.025000,0,0
3,SIWVAQWR,0.0,0.142500,1,0
4,WKTHL,0.0,0.016000,1,0
...,...,...,...,...,...
1846,MMSICLGEF,0.0,0.528889,-1,0
1847,NFHYIWG,0.0,0.420000,0,0
1848,IVTHYAK,0.0,0.198571,1,0
1849,TFNWPSW,0.0,0.274286,0,0
1850,MQSLHS,0.0,0.015000,0,0

In [24]:
valid_fibers = fiber_samples.copy()

for key in fiber_sample:
    valid_fibers = valid_fibers[(valid_fibers[key] >= fiber_sample[key][0]) & ((valid_fibers[key] <= fiber_sample[key][1]))]

valid_fibers

,sequence,beta_sheet_fraction,hydrophobic_moment,net_charge,has_beta_sheet_content
222,AKCTLGFIIF,0.5,0.604,1,1
484,GHYDPCDPKW,0.5,0.162,-1,1
938,FMVDGDFKWP,0.5,0.221,-1,1
1458,CRFYGGVVET,0.5,0.154,0,1

In [26]:
peptide_propensities_fibers = pd.read_csv('./gen_peptides/filtered_ap_peptides_random.txt', names=['sequence', 'sequence_3', 'ap', 'assembly'])
#peptide_propensities_fibers['ap'] = min_max['ap'][0] + (peptide_propensities_fibers['ap'] * (min_max['ap'][1] - min_max['ap'][0]))
peptide_propensities_fibers

        sequence  sequence_3        ap  assembly
0     YRMIHWMMEI          10  1.957391  0.993672
1      RWNYDFWHK           9  1.805670  0.998484
2          LPWHT           5  2.068440  0.999762
3       HWCLPGNN           8  1.878374  0.972086
4         HGIKFA           6  1.852045  0.979549
...          ...         ...       ...       ...
1858  YMWGLRVHDS          10  1.878590  0.992765
1859     FCMPFIM           7  2.151571  0.999898
1860   TTWPWTYNY           9  1.893596  0.999984
1861   PVCAKVFDF           9  1.904546  0.990907
1862    IIHCAAIT           8  1.825752  0.917744

[1863 rows x 4 columns]

In [27]:
merged_valid_fibers = valid_fibers.merge(peptide_propensities_fibers, on='sequence', how='inner')
merged_valid_fibers.sort_values(by='ap', ascending=False)[['sequence', 'sequence_3', 'ap']][:15]

     sequence  sequence_3        ap
1  GHYDPCDPKW          10  1.862551
2  FMVDGDFKWP          10  1.854066
3  CRFYGGVVET          10  1.842635
0  AKCTLGFIIF          10  1.837791

In [28]:
sphere_samples = pd.read_csv('gen_peptides/random_metrics.csv')
sphere_samples.drop(columns=['peptide_id'], inplace=True)
sphere_samples.drop_duplicates(subset=['sequence'], inplace=True)
sphere_samples

        sequence  beta_sheet_fraction  hydrophobic_moment  net_charge
0       TAFFHSVG                  0.0            0.491250           0
1     VYSGTKWVFG                  0.0            0.365000           1
2         WGCQSH                  0.0            0.025000           0
3       SIWVAQWR                  0.0            0.142500           1
4          WKTHL                  0.0            0.016000           1
...          ...                  ...                 ...         ...
1846   MMSICLGEF                  0.0            0.528889          -1
1847     NFHYIWG                  0.0            0.420000           0
1848     IVTHYAK                  0.0            0.198571           1
1849     TFNWPSW                  0.0            0.274286           0
1850      MQSLHS                  0.0            0.015000           0

[1851 rows x 4 columns]

In [29]:
valid_spheres = sphere_samples.copy()

for key in sphere_sample:
    valid_spheres = valid_spheres[(valid_spheres[key] >= sphere_sample[key][0]) & ((valid_spheres[key] <= sphere_sample[key][1]))]

valid_spheres

Empty DataFrame
Columns: [sequence, beta_sheet_fraction, hydrophobic_moment, net_charge]
Index: []

In [31]:
peptide_propensities_spheres = pd.read_csv('./gen_peptides/filtered_ap_peptides_random.txt', names=['sequence', 'sequence_3', 'ap', 'assembly'])
#peptide_propensities_spheres_extra = pd.read_csv('./filtered_ap_peptides_random_spheres_extra.txt', names=['sequence', 'sequence_3', 'ap', 'assembly'])
#peptide_propensities_spheres = pd.concat([peptide_propensities_spheres, peptide_propensities_spheres_extra], ignore_index=True)
#peptide_propensities_spheres['ap'] = min_max['ap'][0] + (peptide_propensities_spheres['ap'] * (min_max['ap'][1] - min_max['ap'][0]))
peptide_propensities_spheres

        sequence  sequence_3        ap  assembly
0     YRMIHWMMEI          10  1.957391  0.993672
1      RWNYDFWHK           9  1.805670  0.998484
2          LPWHT           5  2.068440  0.999762
3       HWCLPGNN           8  1.878374  0.972086
4         HGIKFA           6  1.852045  0.979549
...          ...         ...       ...       ...
1858  YMWGLRVHDS          10  1.878590  0.992765
1859     FCMPFIM           7  2.151571  0.999898
1860   TTWPWTYNY           9  1.893596  0.999984
1861   PVCAKVFDF           9  1.904546  0.990907
1862    IIHCAAIT           8  1.825752  0.917744

[1863 rows x 4 columns]

In [32]:
merged_valid_spheres = valid_spheres.merge(peptide_propensities_spheres, on='sequence', how='inner')
merged_valid_spheres.sort_values(by='ap', ascending=False)[['sequence', 'sequence_3', 'ap']][:15]

Empty DataFrame
Columns: [sequence, sequence_3, ap]
Index: []

In [20]:
merged_valid_spheres.to_csv('valid_spheres_unconditional.csv', index=False)
merged_valid_fibers.to_csv('valid_fibers_unconditional.csv', index=False)